/* =====================================================================
   Personal hub — vanilla JS (interactive behavior only)
   ---------------------------------------------------------------------
   All page content is pre-rendered static HTML (generated by
   scripts/generate-site.js from data/content.js). This script only
   handles interactive enhancement:

     - light / dark theme switching (+ localStorage persistence)
     - mobile navigation menu
     - explicit EN/RU language choice persistence
     - sticky header state
     - active navigation highlighting
     - optional reveal-on-scroll animations
     - copyright year refresh (static fallback exists in the HTML)

   No core content is rendered from JavaScript. With JS disabled every
   section, link and image is still present in the HTML.
   ===================================================================== */

(function () {
  'use strict';

  var root = document.documentElement;

  // Mark that JS is active. The reveal CSS only hides elements under
  // html.js, so with JavaScript unavailable everything stays visible.
  root.classList.add('js');

  function $(sel, ctx) { return (ctx || document).querySelector(sel); }
  function $$(sel, ctx) { return Array.prototype.slice.call((ctx || document).querySelectorAll(sel)); }

  /* ---------- Theme ---------- */
  var themeToggle = $('#theme-toggle');
  var metaTheme = document.querySelector('meta[name="theme-color"]');

  function setTheme(theme) {
    root.setAttribute('data-theme', theme);
    var dark = theme === 'dark';
    if (themeToggle) {
      themeToggle.setAttribute('aria-label', dark ? 'Switch to light theme' : 'Switch to dark theme');
      themeToggle.setAttribute('title', dark ? 'Switch to light theme' : 'Switch to dark theme');
    }
    if (metaTheme) metaTheme.setAttribute('content', dark ? '#0b0e12' : '#faf9f6');
    try { localStorage.setItem('theme', theme); } catch (e) { /* private mode */ }
  }

  if (themeToggle) {
    themeToggle.addEventListener('click', function () {
      setTheme(root.getAttribute('data-theme') === 'dark' ? 'light' : 'dark');
    });
    // Sync aria-label / title / theme-color with the theme chosen on load.
    setTheme(root.getAttribute('data-theme') || 'dark');
  }

  /* =====================================================================
     Route-aware language switching
     ---------------------------------------------------------------------
     The site is three language-aware routes:

         HOME      /          <->  /ru/
         RESUME    /resume/   <->  /ru/resume/
         GAME      /game/     <->  /ru/game/

     Switching language never changes the page context: home stays home,
     resume stays resume, game stays game. The query string is preserved
     and the viewport position is carried over as
     { sectionId, offsetWithinSection } in sessionStorage — not as a raw
     scrollY, because EN and RU versions of the same content have
     different heights. An explicit URL hash on a fresh entry always wins
     over any saved viewport state.
     ===================================================================== */

  var ROUTES = {
    home: { en: '/', ru: '/ru/' },
    resume: { en: '/resume/', ru: '/ru/resume/' },
    game: { en: '/game/', ru: '/ru/game/' }
  };

  var HOME_SECTIONS = ['home', 'projects', 'paths', 'game', 'about', 'work', 'build', 'building', 'findme', 'support'];
  var RESUME_SECTIONS = ['summary', 'experience', 'skills', 'contact'];
  var GAME_SECTIONS = ['game', 'overview', 'media', 'team', 'follow', 'support'];
  var VIEWPORT_STATE_KEY = 'viewport-state';

  function getPageType() {
    var p = window.location.pathname;
    // /resume/ and /ru/resume/ are the resume route; /game/ and /ru/game/
    // are the UndeadOverhaul route; everything else is home.
    if (/\/resume\/?$/.test(p)) return 'resume';
    if (/\/game\/?$/.test(p)) return 'game';
    return 'home';
  }

  function getSections(pageType) {
    if (pageType === 'resume') return RESUME_SECTIONS;
    if (pageType === 'game') return GAME_SECTIONS;
    return HOME_SECTIONS;
  }

  function getPreferredLanguage() {
    var saved = null;
    try { saved = localStorage.getItem('lang'); } catch (e) { /* private mode */ }
    if (saved === 'en' || saved === 'ru') return saved;
    var preferred = String(
      (navigator.languages && navigator.languages.length && navigator.languages[0]) ||
      navigator.language || navigator.userLanguage || 'en'
    ).toLowerCase();
    return preferred.indexOf('ru') === 0 ? 'ru' : 'en';
  }

  function detectCurrentSection(pageType) {
    var ids = getSections(pageType);
    // Reference point: 40% down the visible viewport — the section the user
    // is actually reading, not the one whose top just passed the header.
    var ref = window.scrollY + Math.round(window.innerHeight * 0.4);
    var current = ids[0];
    ids.forEach(function (id) {
      var el = document.getElementById(id);
      if (!el) return;
      var top = el.getBoundingClientRect().top + window.scrollY;
      if (top <= ref) current = id;
    });
    return current;
  }

  function getCurrentViewportState(pageType) {
    var sectionId = detectCurrentSection(pageType);
    var offset = 0;
    var el = document.getElementById(sectionId);
    if (el) {
      // Negative while the section top is still below the viewport top (the
      // sticky-header anchored position), positive once scrolled into it.
      offset = Math.round(-el.getBoundingClientRect().top);
    }
    return {
      pageType: pageType,
      sectionId: sectionId,
      offsetWithinSection: offset,
      ts: Date.now()
    };
  }

  function shouldSetHash(state) {
    var ids = getSections(state.pageType);
    // At the very top of the first section a bare route is cleaner:
    // / -> /ru/  and  /resume/ -> /ru/resume/  (no #home / #summary noise).
    return !(state.sectionId === ids[0] && state.offsetWithinSection <= 0);
  }

  function buildLocalizedUrl(targetLang, state, includeHash) {
    // When viewport state is carried over, the hash is added afterwards via
    // history.replaceState (once the scroll is restored), so the native hash
    // scroll does not fight the restore. includeHash is the fallback for
    // sessions where viewport state cannot be saved.
    var hash = includeHash && shouldSetHash(state) ? '#' + state.sectionId : '';
    return ROUTES[state.pageType][targetLang] + window.location.search + hash;
  }

  function saveViewportState(state) {
    try {
      sessionStorage.setItem(VIEWPORT_STATE_KEY, JSON.stringify(state));
      return true;
    } catch (e) { /* private mode */ return false; }
  }

  function readViewportState() {
    try {
      var raw = sessionStorage.getItem(VIEWPORT_STATE_KEY);
      if (!raw) return null;
      var state = JSON.parse(raw);
      if (!state || typeof state.pageType !== 'string' || typeof state.sectionId !== 'string') return null;
      return state;
    } catch (e) { return null; }
  }

  function clearViewportState() {
    try { sessionStorage.removeItem(VIEWPORT_STATE_KEY); } catch (e) { /* private mode */ }
  }

  function restoreViewportState() {
    var state = readViewportState();
    if (!state) return;
    // Only states produced by a language switch onto this page type apply.
    if (state.pageType !== getPageType()) return;
    // Drop stale states (cancelled navigation, long-lived tabs).
    if (!state.ts || Date.now() - state.ts > 60000) { clearViewportState(); return; }
    var ids = getSections(state.pageType);
    if (ids.indexOf(state.sectionId) === -1) { clearViewportState(); return; }
    var el = document.getElementById(state.sectionId);
    if (!el) { clearViewportState(); return; }
    clearViewportState();

    function apply() {
      var top = el.getBoundingClientRect().top + window.scrollY;
      var y = Math.max(0, top + (state.offsetWithinSection || 0));
      // The page uses CSS scroll-behavior: smooth; force this single scroll
      // to be instant so the position matches exactly.
      var html = document.documentElement;
      var prev = html.style.scrollBehavior;
      html.style.scrollBehavior = 'auto';
      window.scrollTo(0, y);
      html.style.scrollBehavior = prev;

      // Reflect the section in the hash without adding a history entry.
      // Deferred until after load: the browser runs its own fragment scroll
      // early during page load, and a hash present at that moment would
      // override the restored position. After load the hash can be added
      // safely (replaceState does not scroll on its own).
      function setHashAndFix() {
        if (shouldSetHash(state) && window.location.hash !== '#' + state.sectionId) {
          try { history.replaceState(null, '', '#' + state.sectionId); } catch (e) { /* ignore */ }
        }
        // Re-assert the preserved position in case a late fragment scroll
        // moved the page after the restore.
        function assert() {
          var topNow = el.getBoundingClientRect().top + window.scrollY;
          var target = Math.max(0, topNow + (state.offsetWithinSection || 0));
          html.style.scrollBehavior = 'auto';
          window.scrollTo(0, target);
          html.style.scrollBehavior = prev;
        }
        assert();
        requestAnimationFrame(function () { requestAnimationFrame(assert); });
      }

      if (document.readyState === 'complete') {
        setHashAndFix();
      } else {
        window.addEventListener('load', setHashAndFix);
      }
    }

    function whenReady() {
      if (document.fonts && document.fonts.ready) {
        // Restore after fonts have loaded so layout shifts do not leave the
        // viewport at the wrong offset.
        document.fonts.ready.then(apply, apply);
      } else {
        apply();
      }
    }

    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', whenReady);
    } else {
      whenReady();
    }
  }

  function initLanguageSwitch() {
    $$('.lang-link').forEach(function (a) {
      a.addEventListener('click', function (e) {
        var targetLang = (a.getAttribute('lang') || '').toLowerCase();
        if (targetLang !== 'en' && targetLang !== 'ru') return;
        // Let modified clicks (new tab / new window) use the static href.
        if (e.metaKey || e.ctrlKey || e.shiftKey || e.altKey || e.button !== 0) return;
        e.preventDefault();
        // Persist the explicit choice so the target page bootstrap does not
        // auto-redirect the visitor back.
        try { localStorage.setItem('lang', targetLang); } catch (err) { /* private mode */ }
        var state = getCurrentViewportState(getPageType());
        var saved = saveViewportState(state);
        window.location.href = buildLocalizedUrl(targetLang, state, !saved);
      });
    });
  }

  /* ---------- Mobile menu ---------- */
  var menuToggle = $('#menu-toggle');
  var navLinks = $('#nav-links');
  var headerEl = $('#site-header');

  function setMenu(open) {
    if (!menuToggle || !navLinks || !headerEl) return;
    navLinks.classList.toggle('open', open);
    headerEl.classList.toggle('menu-open', open);
    menuToggle.setAttribute('aria-expanded', open ? 'true' : 'false');
    menuToggle.setAttribute('aria-label', open ? 'Close menu' : 'Open menu');
  }

  if (menuToggle && navLinks) {
    menuToggle.addEventListener('click', function () {
      setMenu(!navLinks.classList.contains('open'));
    });
    $$('.nav-link', navLinks).forEach(function (a) {
      a.addEventListener('click', function () { setMenu(false); });
    });
    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape') setMenu(false);
    });
    document.addEventListener('click', function (e) {
      if (navLinks.classList.contains('open') && !e.target.closest('.nav')) setMenu(false);
    });
    window.addEventListener('resize', function () {
      if (window.innerWidth >= 768) setMenu(false);
    });
  }

  /* ---------- Header scrolled state ---------- */
  function onScroll() {
    if (headerEl) headerEl.classList.toggle('is-scrolled', window.scrollY > 8);
  }
  window.addEventListener('scroll', onScroll, { passive: true });
  onScroll();

  /* ---------- Reveal-on-scroll (progressive enhancement) ----------
     Without JavaScript the .reveal elements are never hidden, so the
     whole page is readable even if this block never runs. */
  function initReveal() {
    var els = $$('.reveal');
    if (!els.length) return;
    if (!('IntersectionObserver' in window)) {
      els.forEach(function (el) { el.classList.add('in'); });
      return;
    }
    var io = new IntersectionObserver(function (entries) {
      entries.forEach(function (entry) {
        if (entry.isIntersecting) {
          entry.target.classList.add('in');
          io.unobserve(entry.target);
        }
      });
    }, { threshold: 0.08, rootMargin: '0px 0px -32px 0px' });
    els.forEach(function (el) { io.observe(el); });
  }

  /* ---------- Active nav highlight ---------- */
  function initActiveNav() {
    var links = $$('.nav-link[data-nav]');
    if (!links.length) return;
    var map = {};
    links.forEach(function (a) { map[a.getAttribute('href').slice(1)] = a; });
    var ids = Object.keys(map);
    var ticking = false;

    function update() {
      var pos = window.scrollY + 130;
      var current = ids[0];
      ids.forEach(function (id) {
        var el = document.getElementById(id);
        if (el && el.offsetTop <= pos) current = id;
      });
      links.forEach(function (a) {
        a.classList.toggle('is-active', map[current] === a);
      });
      ticking = false;
    }
    window.addEventListener('scroll', function () {
      if (!ticking) {
        ticking = true;
        window.requestAnimationFrame(update);
      }
    }, { passive: true });
    window.addEventListener('resize', update, { passive: true });
    update();
  }

  /* ---------- Copyright year refresh (static fallback exists in HTML) ---------- */
  function updateYear() {
    var year = $('#year');
    if (year) year.textContent = String(new Date().getFullYear());
  }

  /* ---------- Init ---------- */
  initReveal();
  initActiveNav();
  initLanguageSwitch();
  restoreViewportState();
  updateYear();
})();
