/* =====================================================================
   Personal hub — vanilla JS (interactive behavior only)
   ---------------------------------------------------------------------
   All page content is pre-rendered static HTML (generated by
   scripts/generate-site.js from data/content.js). This script only
   handles interactive enhancement:

     - light / dark theme switching (+ localStorage persistence)
     - mobile navigation menu
     - explicit EN/RU language choice persistence
     - sticky header state
     - active navigation highlighting
     - optional reveal-on-scroll animations
     - copyright year refresh (static fallback exists in the HTML)

   No core content is rendered from JavaScript. With JS disabled every
   section, link and image is still present in the HTML.
   ===================================================================== */

(function () {
  'use strict';

  var root = document.documentElement;

  // Mark that JS is active. The reveal CSS only hides elements under
  // html.js, so with JavaScript unavailable everything stays visible.
  root.classList.add('js');

  function $(sel, ctx) { return (ctx || document).querySelector(sel); }
  function $$(sel, ctx) { return Array.prototype.slice.call((ctx || document).querySelectorAll(sel)); }

  /* ---------- Theme ---------- */
  var themeToggle = $('#theme-toggle');
  var metaTheme = document.querySelector('meta[name="theme-color"]');

  function setTheme(theme) {
    root.setAttribute('data-theme', theme);
    var dark = theme === 'dark';
    if (themeToggle) {
      themeToggle.setAttribute('aria-label', dark ? 'Switch to light theme' : 'Switch to dark theme');
      themeToggle.setAttribute('title', dark ? 'Switch to light theme' : 'Switch to dark theme');
    }
    if (metaTheme) metaTheme.setAttribute('content', dark ? '#0b0e12' : '#faf9f6');
    try { localStorage.setItem('theme', theme); } catch (e) { /* private mode */ }
  }

  if (themeToggle) {
    themeToggle.addEventListener('click', function () {
      setTheme(root.getAttribute('data-theme') === 'dark' ? 'light' : 'dark');
    });
    // Sync aria-label / title / theme-color with the theme chosen on load.
    setTheme(root.getAttribute('data-theme') || 'dark');
  }

  /* ---------- Language switcher: remember explicit choice ----------
     Auto-redirect (head bootstrap) only applies before a first explicit
     choice; once the user picks a language manually, it is stored in
     localStorage and takes precedence over auto-detection. */
  function initLanguageSwitch() {
    $$('.lang-link').forEach(function (a) {
      a.addEventListener('click', function () {
        var target = (a.getAttribute('lang') || '').toLowerCase();
        if (target === 'en' || target === 'ru') {
          try { localStorage.setItem('lang', target); } catch (e) { /* private mode */ }
        }
      });
    });
  }

  /* ---------- Mobile menu ---------- */
  var menuToggle = $('#menu-toggle');
  var navLinks = $('#nav-links');
  var headerEl = $('#site-header');

  function setMenu(open) {
    if (!menuToggle || !navLinks || !headerEl) return;
    navLinks.classList.toggle('open', open);
    headerEl.classList.toggle('menu-open', open);
    menuToggle.setAttribute('aria-expanded', open ? 'true' : 'false');
    menuToggle.setAttribute('aria-label', open ? 'Close menu' : 'Open menu');
  }

  if (menuToggle && navLinks) {
    menuToggle.addEventListener('click', function () {
      setMenu(!navLinks.classList.contains('open'));
    });
    $$('.nav-link', navLinks).forEach(function (a) {
      a.addEventListener('click', function () { setMenu(false); });
    });
    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape') setMenu(false);
    });
    document.addEventListener('click', function (e) {
      if (navLinks.classList.contains('open') && !e.target.closest('.nav')) setMenu(false);
    });
    window.addEventListener('resize', function () {
      if (window.innerWidth >= 768) setMenu(false);
    });
  }

  /* ---------- Header scrolled state ---------- */
  function onScroll() {
    if (headerEl) headerEl.classList.toggle('is-scrolled', window.scrollY > 8);
  }
  window.addEventListener('scroll', onScroll, { passive: true });
  onScroll();

  /* ---------- Reveal-on-scroll (progressive enhancement) ----------
     Without JavaScript the .reveal elements are never hidden, so the
     whole page is readable even if this block never runs. */
  function initReveal() {
    var els = $$('.reveal');
    if (!els.length) return;
    if (!('IntersectionObserver' in window)) {
      els.forEach(function (el) { el.classList.add('in'); });
      return;
    }
    var io = new IntersectionObserver(function (entries) {
      entries.forEach(function (entry) {
        if (entry.isIntersecting) {
          entry.target.classList.add('in');
          io.unobserve(entry.target);
        }
      });
    }, { threshold: 0.08, rootMargin: '0px 0px -32px 0px' });
    els.forEach(function (el) { io.observe(el); });
  }

  /* ---------- Active nav highlight ---------- */
  function initActiveNav() {
    var links = $$('.nav-link[data-nav]');
    if (!links.length) return;
    var map = {};
    links.forEach(function (a) { map[a.getAttribute('href').slice(1)] = a; });
    var ids = Object.keys(map);
    var ticking = false;

    function update() {
      var pos = window.scrollY + 130;
      var current = ids[0];
      ids.forEach(function (id) {
        var el = document.getElementById(id);
        if (el && el.offsetTop <= pos) current = id;
      });
      links.forEach(function (a) {
        a.classList.toggle('is-active', map[current] === a);
      });
      ticking = false;
    }
    window.addEventListener('scroll', function () {
      if (!ticking) {
        ticking = true;
        window.requestAnimationFrame(update);
      }
    }, { passive: true });
    window.addEventListener('resize', update, { passive: true });
    update();
  }

  /* ---------- Copyright year refresh (static fallback exists in HTML) ---------- */
  function updateYear() {
    var year = $('#year');
    if (year) year.textContent = String(new Date().getFullYear());
  }

  /* ---------- Init ---------- */
  initReveal();
  initActiveNav();
  initLanguageSwitch();
  updateYear();
})();
