/* Headless smoke test for the dedicated personal / about pages
   (/about/ and /ru/about/).

   The about pages are generated at build time by scripts/generate-site.js
   from data/content.js, exactly like the home, resume and game pages. This
   test reads the generated HTML directly — no browser, no JavaScript
   execution — and verifies the full personal context is present in raw
   HTML: identity hero, story, what I build, the workbench terminal and a
   work-with-me CTA. That is the no-JS acceptance criterion for the about
   layer.

   It also exercises the language bootstrap embedded in each about page
   (explicit EN/RU choice always wins; crawlers are never redirected) and
   verifies the language switch hrefs resolve to the sibling route.
*/
'use strict';
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.join(__dirname, '..');
const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');

/* Extract the inner HTML of <tag id="..."> ... </tag> (tag-depth aware). */
function innerOf(html, id) {
  const re = new RegExp('<([a-zA-Z][a-zA-Z0-9]*)\\b[^>]*\\bid="' + id + '"[^>]*>');
  const m = re.exec(html);
  if (!m) return null;
  const tag = m[1];
  const openEnd = m.index + m[0].length;
  const openRe = new RegExp('<' + tag + '\\b', 'g');
  const closeRe = new RegExp('</' + tag + '>', 'g');
  let depth = 1;
  let i = openEnd;
  openRe.lastIndex = i;
  closeRe.lastIndex = i;
  for (;;) {
    const o = openRe.exec(html);
    const c = closeRe.exec(html);
    if (!c) return null;
    if (o && o.index < c.index) { depth += 1; i = o.index + 1; }
    else { depth -= 1; if (depth === 0) return html.slice(openEnd, c.index); i = c.index + 1; }
    openRe.lastIndex = i;
    closeRe.lastIndex = i;
  }
}

function runChecks(html, lang) {
  const r = {};
  const add = (name, ok) => { r[name] = !!ok; };
  const isRu = lang === 'ru';
  const depth = isRu ? 2 : 1;

  /* --- Build marker + architecture --- */
  add('generated-banner', html.includes('Generated by scripts/generate-site.js'));
  add('html-lang', html.includes('<html lang="' + lang + '"'));
  add('no-content-script', !/<script[^>]*src="[^"]*data\/content\.js"/.test(html));

  /* --- Metadata / SEO present in raw HTML --- */
  add('title', html.includes(isRu ? 'Обо мне — EryyynIT / Михаил' : 'About — EryyynIT / Michael'));
  add('description', /name="description" content="[^"]+"/.test(html));
  add('canonical', html.includes('rel="canonical"') &&
    html.includes(isRu ? 'https://eryyynit.github.io/ru/about/">' : 'https://eryyynit.github.io/about/">'));
  add('hreflang', html.includes('hreflang="en"') && html.includes('hreflang="ru"') && html.includes('hreflang="x-default"'));
  add('og', html.includes('property="og:title"') && html.includes('property="og:image"'));
  add('twitter', html.includes('name="twitter:card"') && html.includes('name="twitter:image"'));

  /* --- Identity hero --- */
  const name = innerOf(html, 'about-name') || '';
  add('about-name', name.includes('EryyynIT') && name.includes(isRu ? 'Михаил' : 'Michael'));
  add('about-role', (innerOf(html, 'about-role') || '').includes('Backend'));
  add('about-intro', (innerOf(html, 'about-intro') || '').length > 40);
  add('back-to-hub', html.includes('class="resume-breadcrumb"') &&
    html.includes(isRu ? 'href="../../"' : 'href="../"'));

  /* --- Story (complete personal context) --- */
  const story = innerOf(html, 'about-story') || '';
  add('story-paragraphs', (story.match(/<p>/g) || []).length === 3);
  add('story-identity', story.includes('EryyynIT') && story.includes(isRu ? 'Михаил' : 'Michael'));

  /* --- What I build (relocated from Home) --- */
  const build = innerOf(html, 'about-build-grid') || '';
  add('build-cards', (build.match(/<article class="card build-card reveal">/g) || []).length === 3);
  add('build-titles', isRu
    ? build.includes('Backend') && build.includes('Инфраструктура') && build.includes('Эксперименты')
    : build.includes('Backend') && build.includes('Infrastructure') && build.includes('Experiments'));

  /* --- Workbench terminal (relocated from Home) --- */
  const building = innerOf(html, 'about-building-lines') || '';
  add('building-lines', (building.match(/role="listitem"/g) || []).length === 3);
  add('building-game-link', building.includes(isRu ? 'href="../../game/"' : 'href="../game/') &&
    building.includes('UndeadOverhaul'));

  /* --- Work with me --- */
  add('work-cta', html.includes('https://t.me/eprintln') && html.includes('contact-band'));

  /* --- Semantic structure --- */
  add('semantic', /<article\b/.test(html) && /<section\b/.test(html) && /<nav\b/.test(html) && /<main\b/.test(html));
  add('skip-link', html.includes('class="skip-link"'));

  /* --- Cross-links to hub / resume / game --- */
  add('resume-link', html.includes(isRu ? '../../ru/resume/' : '../resume/'));
  add('game-link', html.includes(isRu ? '../../ru/game/' : '../game/'));

  /* --- No stale /personal-hub/ URLs, no placeholders --- */
  add('no-personal-hub-url', !html.includes('/personal-hub/'));
  add('no-placeholder-wording', !html.toLowerCase().includes('placeholder'));

  /* --- Language switch href must resolve to the sibling route --- */
  add('lang-switch-resolves', (() => {
    const m = html.match(/<a class="lang-link" href="([^"]+)"/);
    if (!m) return false;
    try {
      const base = isRu ? 'http://localhost:8080/ru/about/' : 'http://localhost:8080/about/';
      const want = isRu ? 'http://localhost:8080/about/' : 'http://localhost:8080/ru/about/';
      return new URL(m[1], base).href === want;
    } catch (e) { return false; }
  })());

  /* --- Relative URL integrity: every relative src/href must resolve --- */
  const refs = [...html.matchAll(/(?:href|src)="([^"]+)"/g)].map((m) => m[1]);
  const relative = refs.filter((u) => !u.startsWith('#') && !u.startsWith('http') && !u.startsWith('data:') && !u.startsWith('mailto:'));
  const missing = relative
    .map((u) => {
      if (depth === 2 && u.startsWith('../../')) return u.slice(6);
      if (u.startsWith('../')) return u.slice(3);
      return u;
    })
    .filter((u) => !fs.existsSync(path.join(ROOT, u)));
  add('relative-assets-resolve', missing.length === 0);
  r.relativeRefs = relative;
  r.missingFiles = missing;

  return r;
}

const en = runChecks(read('about/index.html'), 'en');
const ru = runChecks(read('ru/about/index.html'), 'ru');

/* =====================================================================
   Language bootstrap for the about pages
   ===================================================================== */
function extractBootstrap(html) {
  const markerPos = html.indexOf('Language bootstrap');
  if (markerPos === -1) throw new Error('Language bootstrap marker missing');
  const open = html.indexOf('<script>', markerPos);
  const close = html.indexOf('</script>', open);
  return html.slice(open + '<script>'.length, close).trim();
}

const enScript = extractBootstrap(read('about/index.html'));
const ruScript = extractBootstrap(read('ru/about/index.html'));

function runLang(script, pageLang, opts) {
  opts = opts || {};
  const store = {};
  if (opts.saved) store.lang = opts.saved;
  const calls = [];
  const sandbox = {
    document: { documentElement: { getAttribute: (k) => (k === 'lang' ? pageLang : null) } },
    navigator: {
      languages: opts.languages,
      language: opts.language,
      userLanguage: opts.userLanguage,
      userAgent: opts.userAgent,
      webdriver: opts.webdriver
    },
    location: {
      replace: (u) => calls.push(String(u)),
      search: opts.search || '',
      hash: opts.hash || ''
    },
    localStorage: {
      getItem: (k) => (k in store ? store[k] : null),
      setItem: () => {}
    }
  };
  let threw = false;
  try {
    vm.runInNewContext(script, sandbox, { filename: 'about-lang-bootstrap.js' });
  } catch (e) {
    threw = true;
  }
  return { calls, threw };
}

function langCheck(name, script, pageLang, opts, expected) {
  const r = runLang(script, pageLang, opts);
  const pass = !r.threw && JSON.stringify(r.calls) === JSON.stringify(expected);
  return { name, pass, expected, calls: r.calls, threw: r.threw };
}

const langCases = [
  langCheck('EN about, saved=ru -> ../ru/about/', enScript, 'en', { saved: 'ru', language: 'en' }, ['../ru/about/']),
  langCheck('EN about, ru-preferred browser -> ../ru/about/', enScript, 'en', { language: 'ru-RU' }, ['../ru/about/']),
  langCheck('EN about, en-preferred browser -> stay', enScript, 'en', { language: 'en-US' }, []),
  langCheck('EN about, saved=en, ru-preferred browser -> stay', enScript, 'en', { saved: 'en', language: 'ru' }, []),
  langCheck('EN about, googlebot, ru-preferred -> stay', enScript, 'en', {
    userAgent: 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)', language: 'ru-RU'
  }, []),
  langCheck('RU about, saved=en -> ../../about/', ruScript, 'ru', { saved: 'en', language: 'ru' }, ['../../about/']),
  langCheck('RU about, en-preferred browser -> ../../about/', ruScript, 'ru', { language: 'en-US' }, ['../../about/']),
  langCheck('RU about, ru-preferred browser -> stay', ruScript, 'ru', { language: 'ru-RU' }, []),
  langCheck('RU about, saved=ru, en-preferred browser -> stay', ruScript, 'ru', { saved: 'ru', language: 'en' }, []),
  langCheck('RU about, bingbot, en-preferred -> stay', ruScript, 'ru', {
    userAgent: 'Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)', language: 'en-US'
  }, []),
  langCheck('EN about, saved=ru, #story -> ../ru/about/#story',
    enScript, 'en', { saved: 'ru', language: 'en', hash: '#story' }, ['../ru/about/#story']),
  langCheck('EN about, saved=ru, ?source=x#story -> ../ru/about/?source=x#story',
    enScript, 'en', { saved: 'ru', language: 'en', search: '?source=x', hash: '#story' }, ['../ru/about/?source=x#story']),
  langCheck('RU about, saved=en, #build -> ../../about/#build',
    ruScript, 'ru', { saved: 'en', language: 'ru', hash: '#build' }, ['../../about/#build']),
  langCheck('RU about, saved=en, ?source=x#build -> ../../about/?source=x#build',
    ruScript, 'ru', { saved: 'en', language: 'ru', search: '?source=x', hash: '#build' }, ['../../about/?source=x#build'])
];

/* --- Bootstrap redirect targets must resolve to real pages --- */
function extractBootPath(html) {
  const m = html.match(/location\.replace\('([^']+)'\s*\+\s*suffix\)/);
  return m ? m[1] : null;
}
const enBootTarget = extractBootPath(read('about/index.html'));
const ruBootTarget = extractBootPath(read('ru/about/index.html'));
const bootResolve = [
  {
    name: 'EN bootstrap target resolves to /ru/about/',
    pass: !!enBootTarget && new URL(enBootTarget, 'http://localhost:8080/about/').href === 'http://localhost:8080/ru/about/'
  },
  {
    name: 'RU bootstrap target resolves to /about/',
    pass: !!ruBootTarget && new URL(ruBootTarget, 'http://localhost:8080/ru/about/').href === 'http://localhost:8080/about/'
  }
];

const report = { en, ru, langBootstrap: langCases, bootResolve };
console.log(JSON.stringify(report, null, 2));

let pass = true;
['en', 'ru'].forEach((lang) => {
  Object.entries(report[lang]).forEach(([k, v]) => {
    if (k === 'relativeRefs') return;
    if (v === false || (Array.isArray(v) && v.length)) {
      pass = false;
      console.error('FAIL [' + lang + ']:', k, v);
    }
  });
});
langCases.forEach((c) => {
  if (!c.pass) { pass = false; console.error('FAIL [lang]:', c.name, c); }
});
bootResolve.forEach((b) => {
  if (!b.pass) { pass = false; console.error('FAIL [boot]:', b.name); }
});

if (!pass) process.exit(1);
console.log('\n✓ ALL ABOUT PRERENDER + LANGUAGE CHECKS PASSED (EN + RU)');
