/* Headless smoke test for the dedicated UndeadOverhaul pages
   (/game/ and /ru/game/).

   The game pages are generated at build time by scripts/generate-site.js
   from data/content.js, exactly like the home and resume pages. This test
   reads the generated HTML directly — no browser, no JavaScript execution —
   and verifies the whole game context is present in raw HTML: hero,
   overview, media, team, follow links and support. That is the no-JS
   acceptance criterion for the game layer.

   It also exercises the language bootstrap embedded in each game page
   (explicit EN/RU choice always wins; crawlers are never redirected) and
   verifies the language switch hrefs resolve to the sibling route.
*/
'use strict';
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.join(__dirname, '..');
const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');

/* Extract the inner HTML of <tag id="..."> ... </tag> (tag-depth aware). */
function innerOf(html, id) {
  const re = new RegExp('<([a-zA-Z][a-zA-Z0-9]*)\\b[^>]*\\bid="' + id + '"[^>]*>');
  const m = re.exec(html);
  if (!m) return null;
  const tag = m[1];
  const openEnd = m.index + m[0].length;
  const openRe = new RegExp('<' + tag + '\\b', 'g');
  const closeRe = new RegExp('</' + tag + '>', 'g');
  let depth = 1;
  let i = openEnd;
  openRe.lastIndex = i;
  closeRe.lastIndex = i;
  for (;;) {
    const o = openRe.exec(html);
    const c = closeRe.exec(html);
    if (!c) return null;
    if (o && o.index < c.index) { depth += 1; i = o.index + 1; }
    else { depth -= 1; if (depth === 0) return html.slice(openEnd, c.index); i = c.index + 1; }
    openRe.lastIndex = i;
    closeRe.lastIndex = i;
  }
}

function runChecks(html, lang) {
  const r = {};
  const add = (name, ok) => { r[name] = !!ok; };
  const isRu = lang === 'ru';
  const depth = isRu ? 2 : 1;

  /* --- Build marker + architecture --- */
  add('generated-banner', html.includes('Generated by scripts/generate-site.js'));
  add('html-lang', html.includes('<html lang="' + lang + '"'));
  add('no-content-script', !/<script[^>]*src="[^"]*data\/content\.js"/.test(html));

  /* --- Metadata / SEO present in raw HTML --- */
  add('title', html.includes(isRu ? 'инди-игра в разработке' : 'An indie game in development'));
  add('description', /name="description" content="[^"]+"/.test(html));
  add('canonical', html.includes('rel="canonical"') &&
    html.includes(isRu ? 'https://eryyynit.github.io/ru/game/">' : 'https://eryyynit.github.io/game/">'));
  add('hreflang', html.includes('hreflang="en"') && html.includes('hreflang="ru"') && html.includes('hreflang="x-default"'));
  add('og', html.includes('property="og:title"') && html.includes('property="og:image"'));
  add('twitter', html.includes('name="twitter:card"') && html.includes('name="twitter:image"'));

  /* --- Game hero --- */
  add('game-title', (innerOf(html, 'game-title') || '').includes('UndeadOverhaul'));
  add('game-tagline', (innerOf(html, 'game-tagline') || '')
    .includes(isRu ? 'Инди-игра в активной разработке' : 'An indie game in active development'));
  add('game-status', (innerOf(html, 'game-status') || '').includes(isRu ? 'В разработке' : 'In development'));
  add('game-cover', (innerOf(html, 'game-cover') || '').includes('assets/game/cover.svg'));
  add('hero-devlog-cta', html.includes('https://t.me/undeadoverhaul'));

  /* --- Overview --- */
  add('game-desc', (innerOf(html, 'game-desc') || '').length > 100);
  const facts = innerOf(html, 'game-facts') || '';
  add('game-facts', facts.includes(isRu ? 'Статус' : 'Status') && facts.includes(isRu ? 'Команда' : 'Team'));

  /* --- Media --- */
  const gallery = innerOf(html, 'game-gallery') || '';
  add('game-gallery', (gallery.match(/<figure class="game-shot">/g) || []).length === 3);
  add('game-gallery-images',
    gallery.includes('screenshot-01.svg') && gallery.includes('screenshot-02.svg') && gallery.includes('concept-01.svg'));

  /* --- Team --- */
  const team = innerOf(html, 'game-team') || '';
  add('team-cards', (team.match(/<article class="card team-card reveal">/g) || []).length === 2);
  add('team-dev-links', team.includes('https://x.com/EryyynIT') && team.includes('https://www.tiktok.com/@barbaris.yt'));
  add('team-artist-links', team.includes('https://x.com/Gemaglobin1') && team.includes('https://boosty.to/manevr'));
  add('team-artist-note', team.includes('Bread Catto'));

  /* --- Follow (game links) --- */
  const links = innerOf(html, 'game-links') || '';
  add('links-devlog', links.includes('https://t.me/undeadoverhaul'));
  add('links-dev-socials', links.includes('https://x.com/EryyynIT') && links.includes('https://www.tiktok.com/@barbaris.yt'));
  add('links-artist-socials', links.includes('https://x.com/Gemaglobin1') && links.includes('https://boosty.to/manevr'));

  /* --- Support --- */
  add('support-intro', (innerOf(html, 'game-support-intro') || '').length > 40);
  const support = innerOf(html, 'game-support-grid') || '';
  add('support-cards', (support.match(/class="card support-card reveal">/g) || []).length === 2);
  add('support-me', support.includes('https://boosty.to/eryyynit') && support.includes('btn-primary'));
  add('support-artist', support.includes('https://boosty.to/manevr'));

  /* --- Semantic structure --- */
  add('semantic', /<article\b/.test(html) && /<section\b/.test(html) && /<nav\b/.test(html) && /<main\b/.test(html));
  add('skip-link', html.includes('class="skip-link"'));

  /* --- Cross-links back to hub / resume --- */
  add('back-to-hub', html.includes('class="game-breadcrumb"') &&
    html.includes(isRu ? 'href="../../"' : 'href="../"'));
  add('resume-link', html.includes(isRu ? '../../ru/resume/' : '../resume/'));

  /* --- No stale /personal-hub/ URLs, no invented game metadata --- */
  add('no-personal-hub-url', !html.includes('/personal-hub/'));
  add('no-placeholder-wording', !html.toLowerCase().includes('placeholder'));
  add('no-invented-facts',
    !html.toLowerCase().includes('release date') &&
    !html.toLowerCase().includes('steam') &&
    !html.includes('player count') &&
    !html.toLowerCase().includes('achievements'));

  /* --- Language switch href must resolve to the sibling route --- */
  add('lang-switch-resolves', (() => {
    const m = html.match(/<a class="lang-link" href="([^"]+)"/);
    if (!m) return false;
    try {
      const base = isRu ? 'http://localhost:8080/ru/game/' : 'http://localhost:8080/game/';
      const want = isRu ? 'http://localhost:8080/game/' : 'http://localhost:8080/ru/game/';
      return new URL(m[1], base).href === want;
    } catch (e) { return false; }
  })());

  /* --- Relative URL integrity: every relative src/href must resolve --- */
  const refs = [...html.matchAll(/(?:href|src)="([^"]+)"/g)].map((m) => m[1]);
  const relative = refs.filter((u) => !u.startsWith('#') && !u.startsWith('http') && !u.startsWith('data:') && !u.startsWith('mailto:'));
  const missing = relative
    .map((u) => {
      if (depth === 2 && u.startsWith('../../')) return u.slice(6);
      if (u.startsWith('../')) return u.slice(3);
      return u;
    })
    .filter((u) => !fs.existsSync(path.join(ROOT, u)));
  add('relative-assets-resolve', missing.length === 0);
  r.relativeRefs = relative;
  r.missingFiles = missing;

  return r;
}

const en = runChecks(read('game/index.html'), 'en');
const ru = runChecks(read('ru/game/index.html'), 'ru');

/* =====================================================================
   Language bootstrap for the game pages
   ===================================================================== */
function extractBootstrap(html) {
  const markerPos = html.indexOf('Language bootstrap');
  if (markerPos === -1) throw new Error('Language bootstrap marker missing');
  const open = html.indexOf('<script>', markerPos);
  const close = html.indexOf('</script>', open);
  return html.slice(open + '<script>'.length, close).trim();
}

const enScript = extractBootstrap(read('game/index.html'));
const ruScript = extractBootstrap(read('ru/game/index.html'));

function runLang(script, pageLang, opts) {
  opts = opts || {};
  const store = {};
  if (opts.saved) store.lang = opts.saved;
  const calls = [];
  const sandbox = {
    document: { documentElement: { getAttribute: (k) => (k === 'lang' ? pageLang : null) } },
    navigator: {
      languages: opts.languages,
      language: opts.language,
      userLanguage: opts.userLanguage,
      userAgent: opts.userAgent,
      webdriver: opts.webdriver
    },
    location: {
      replace: (u) => calls.push(String(u)),
      search: opts.search || '',
      hash: opts.hash || ''
    },
    localStorage: {
      getItem: (k) => (k in store ? store[k] : null),
      setItem: () => {}
    }
  };
  let threw = false;
  try {
    vm.runInNewContext(script, sandbox, { filename: 'game-lang-bootstrap.js' });
  } catch (e) {
    threw = true;
  }
  return { calls, threw };
}

function langCheck(name, script, pageLang, opts, expected) {
  const r = runLang(script, pageLang, opts);
  const pass = !r.threw && JSON.stringify(r.calls) === JSON.stringify(expected);
  return { name, pass, expected, calls: r.calls, threw: r.threw };
}

const langCases = [
  langCheck('EN game, saved=ru -> ../ru/game/', enScript, 'en', { saved: 'ru', language: 'en' }, ['../ru/game/']),
  langCheck('EN game, ru-preferred browser -> ../ru/game/', enScript, 'en', { language: 'ru-RU' }, ['../ru/game/']),
  langCheck('EN game, en-preferred browser -> stay', enScript, 'en', { language: 'en-US' }, []),
  langCheck('EN game, saved=en, ru-preferred browser -> stay', enScript, 'en', { saved: 'en', language: 'ru' }, []),
  langCheck('EN game, googlebot, ru-preferred -> stay', enScript, 'en', {
    userAgent: 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)', language: 'ru-RU'
  }, []),
  langCheck('RU game, saved=en -> ../../game/', ruScript, 'ru', { saved: 'en', language: 'ru' }, ['../../game/']),
  langCheck('RU game, en-preferred browser -> ../../game/', ruScript, 'ru', { language: 'en-US' }, ['../../game/']),
  langCheck('RU game, ru-preferred browser -> stay', ruScript, 'ru', { language: 'ru-RU' }, []),
  langCheck('RU game, saved=ru, en-preferred browser -> stay', ruScript, 'ru', { saved: 'ru', language: 'en' }, []),
  langCheck('RU game, bingbot, en-preferred -> stay', ruScript, 'ru', {
    userAgent: 'Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)', language: 'en-US'
  }, []),
  langCheck('EN game, saved=ru, #team -> ../ru/game/#team',
    enScript, 'en', { saved: 'ru', language: 'en', hash: '#team' }, ['../ru/game/#team']),
  langCheck('EN game, saved=ru, ?source=x#team -> ../ru/game/?source=x#team',
    enScript, 'en', { saved: 'ru', language: 'en', search: '?source=x', hash: '#team' }, ['../ru/game/?source=x#team']),
  langCheck('RU game, saved=en, #support -> ../../game/#support',
    ruScript, 'ru', { saved: 'en', language: 'ru', hash: '#support' }, ['../../game/#support']),
  langCheck('RU game, saved=en, ?source=x#support -> ../../game/?source=x#support',
    ruScript, 'ru', { saved: 'en', language: 'ru', search: '?source=x', hash: '#support' }, ['../../game/?source=x#support'])
];

const report = { en, ru, langBootstrap: langCases };
console.log(JSON.stringify(report, null, 2));

let pass = true;
['en', 'ru'].forEach((lang) => {
  Object.entries(report[lang]).forEach(([k, v]) => {
    if (k === 'relativeRefs') return;
    if (v === false || (Array.isArray(v) && v.length)) {
      pass = false;
      console.error('FAIL [' + lang + ']:', k, v);
    }
  });
});
langCases.forEach((c) => {
  if (!c.pass) { pass = false; console.error('FAIL [lang]:', c.name, c); }
});

if (!pass) process.exit(1);
console.log('\n✓ ALL GAME PAGE PRERENDER + LANGUAGE CHECKS PASSED (EN + RU)');
