/* Headless smoke test for the pre-rendered resume / professional profile
   pages (/resume/ and /ru/resume/).

   The resume pages are generated at build time by scripts/generate-site.js
   from data/content.js, exactly like the home pages. This test reads the
   generated HTML directly — no browser, no JavaScript execution — and
   verifies that the whole professional profile is present in raw HTML:
   name, summary, every experience entry, skills, contact links and the
   PDF download CTA. That is the no-JS acceptance criterion for the
   resume layer.

   It also exercises the language bootstrap embedded in each resume page
   (explicit EN/RU choice always wins; crawlers are never redirected).
*/
'use strict';
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.join(__dirname, '..');
const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');

/* Extract the inner HTML of <tag id="..."> ... </tag> (tag-depth aware). */
function innerOf(html, id) {
  const re = new RegExp('<([a-zA-Z][a-zA-Z0-9]*)\\b[^>]*\\bid="' + id + '"[^>]*>');
  const m = re.exec(html);
  if (!m) return null;
  const tag = m[1];
  const openEnd = m.index + m[0].length;
  const openRe = new RegExp('<' + tag + '\\b', 'g');
  const closeRe = new RegExp('</' + tag + '>', 'g');
  let depth = 1;
  let i = openEnd;
  openRe.lastIndex = i;
  closeRe.lastIndex = i;
  for (;;) {
    const o = openRe.exec(html);
    const c = closeRe.exec(html);
    if (!c) return null;
    if (o && o.index < c.index) { depth += 1; i = o.index + 1; }
    else { depth -= 1; if (depth === 0) return html.slice(openEnd, c.index); i = c.index + 1; }
    openRe.lastIndex = i;
    closeRe.lastIndex = i;
  }
}

function runChecks(html, lang) {
  const r = {};
  const add = (name, ok) => { r[name] = !!ok; };
  const isRu = lang === 'ru';
  const depth = isRu ? 2 : 1;

  /* --- Build marker + architecture --- */
  add('generated-banner', html.includes('Generated by scripts/generate-site.js'));
  add('html-lang', html.includes('<html lang="' + lang + '"'));
  add('no-content-script', !/<script[^>]*src="[^"]*data\/content\.js"/.test(html));

  /* --- Metadata / SEO present in raw HTML --- */
  add('title', html.includes(isRu ? 'Михаил Баркалов — Backend Developer · Go / Python' : 'Michael Barkalov — Backend Developer · Go / Python'));
  add('description', /name="description" content="[^"]+"/.test(html));
  add('canonical', html.includes('rel="canonical"') &&
    html.includes(isRu ? 'https://eryyynit.github.io/ru/resume/">' : 'https://eryyynit.github.io/resume/">'));
  add('hreflang', html.includes('hreflang="en"') && html.includes('hreflang="ru"') && html.includes('hreflang="x-default"'));
  add('og', html.includes('property="og:title"') && html.includes('property="og:image"'));
  add('twitter', html.includes('name="twitter:card"') && html.includes('name="twitter:image"'));

  /* --- Header --- */
  add('name', (innerOf(html, 'resume-name') || '').includes(isRu ? 'Михаил Баркалов' : 'Michael Barkalov'));
  add('role', (innerOf(html, 'resume-role') || '').includes('Backend Developer · Go / Python'));
  const meta = innerOf(html, 'resume-meta') || '';
  add('meta-line',
    meta.includes('barkalovmisha@gmail.com') &&
    meta.includes('t.me/eprintln') &&
    meta.includes('github.com/EryyynIT') &&
    meta.includes('Remote') &&
    meta.includes('English C1'));
  add('back-to-hub', html.includes('class="resume-breadcrumb"') && html.includes('href="../"'));

  /* --- Summary (from the source CV) --- */
  add('summary', (innerOf(html, 'resume-summary') || '')
    .includes(isRu ? 'Backend-разработчик с 2+ годами production-опыта' : '2+ years of production experience'));

  /* --- Experience: every entry from the CV in raw HTML --- */
  const exp = innerOf(html, 'resume-experience') || '';
  add('experience-adnova', exp.includes('>ADNova</h4>') && exp.includes(isRu ? 'Golang Developer · Москва' : 'Golang Developer · Moscow'));
  add('experience-fintech', exp.includes(isRu ? 'Финтех-платформа (NDA)' : 'Fintech Platform (Confidential)') &&
    exp.includes('Tech Lead / Python Developer'));
  add('experience-kickthedoll', exp.includes('>KickTheDoll</h4>') && exp.includes('FastAPI') && exp.includes('SQLAlchemy'));
  add('experience-escapeiq', exp.includes('>EscapeIQ</h4>') && exp.includes('aiogram') && exp.includes('Pyrogram'));
  add('experience-dates', exp.includes(isRu ? 'Декабрь 2025 – Март 2026' : 'Dec 2025 – Mar 2026') &&
    exp.includes(isRu ? 'Ноябрь 2023 – Декабрь 2025' : 'Nov 2023 – Dec 2025'));
  add('experience-groups', exp.includes(isRu ? 'Коммерческий опыт' : 'Commercial Experience') &&
    exp.includes(isRu ? 'Фриланс и проекты' : 'Freelance &amp; Project Experience'));
  add('experience-results', exp.includes(isRu ? 'Результат:' : 'Result:'));
  add('experience-ru-providers', !isRu || exp.includes('Газпромбанк'));

  /* --- Skills --- */
  const skills = innerOf(html, 'resume-skills') || '';
  add('skills-core',
    skills.includes('Go') && skills.includes('Python') && skills.includes('FastAPI') &&
    skills.includes('PostgreSQL') && skills.includes('Redis') && skills.includes('MySQL') &&
    skills.includes('Kubernetes') && skills.includes('Docker') && skills.includes('GitHub Actions'));
  add('skills-security', skills.includes('OAuth 2.0') && skills.includes('JWT') && skills.includes('TOTP') && skills.includes('RBAC'));
  add('skills-patterns', skills.includes('Event sourcing') && skills.includes('financial reconciliation'));
  add('skills-languages', skills.includes(isRu ? 'Русский — родной' : 'Russian — Native') &&
    skills.includes(isRu ? 'Английский — C1 (Advanced)' : 'English — C1'));

  /* --- PDF download CTA --- */
  const pdfCta = innerOf(html, 'resume-pdf-cta') || '';
  add('pdf-cta',
    pdfCta.includes(isRu ? 'Скачать PDF' : 'Download PDF') &&
    pdfCta.includes('download') &&
    pdfCta.includes(isRu ? '../../assets/cv/MikhailBarkalov_CV_RU.pdf' : '../assets/cv/MichaelBarkalov_CV.pdf'));

  /* --- Contact --- */
  add('contact-heading', (innerOf(html, 'resume-contact-title') || '')
    .includes(isRu ? 'Интересно поработать вместе?' : 'Interested in working together?'));
  const contact = innerOf(html, 'resume-contact') || '';
  add('contact-links',
    contact.includes('mailto:barkalovmisha@gmail.com') &&
    contact.includes('https://t.me/eprintln') &&
    contact.includes('https://github.com/EryyynIT'));
  add('contact-no-phone', !contact.includes('tel:'));
  add('no-linkedin', !/linkedin/i.test(html));
  add('no-form', !/<form/i.test(html));

  /* --- Semantic structure --- */
  add('semantic', /<article\b/.test(html) && /<section\b/.test(html) && /<nav\b/.test(html) && /<main\b/.test(html));
  add('article-count', (html.match(/<article/g) || []).length === 4);
  add('skip-link', html.includes('class="skip-link"'));

  /* --- No stale /personal-hub/ URLs, no placeholders --- */
  add('no-personal-hub-url', !html.includes('/personal-hub/'));
  add('no-placeholder-wording', !html.toLowerCase().includes('placeholder'));

  /* --- Relative URL integrity: every relative src/href must resolve --- */
  const refs = [...html.matchAll(/(?:href|src)="([^"]+)"/g)].map((m) => m[1]);
  const relative = refs.filter((u) => !u.startsWith('#') && !u.startsWith('http') && !u.startsWith('data:') && !u.startsWith('mailto:'));
  const missing = relative
    .map((u) => {
      if (depth === 2 && u.startsWith('../../')) return u.slice(6);
      if (u.startsWith('../')) return u.slice(3);
      return u;
    })
    .filter((u) => !fs.existsSync(path.join(ROOT, u)));
  add('relative-assets-resolve', missing.length === 0);
  r.relativeRefs = relative;
  r.missingFiles = missing;

  return r;
}

const en = runChecks(read('resume/index.html'), 'en');
const ru = runChecks(read('ru/resume/index.html'), 'ru');

/* =====================================================================
   Language bootstrap for the resume pages
   ===================================================================== */
function extractBootstrap(html) {
  const markerPos = html.indexOf('Language bootstrap');
  if (markerPos === -1) throw new Error('Language bootstrap marker missing');
  const open = html.indexOf('<script>', markerPos);
  const close = html.indexOf('</script>', open);
  return html.slice(open + '<script>'.length, close).trim();
}

const enScript = extractBootstrap(read('resume/index.html'));
const ruScript = extractBootstrap(read('ru/resume/index.html'));

function runLang(script, pageLang, opts) {
  opts = opts || {};
  const store = {};
  if (opts.saved) store.lang = opts.saved;
  const calls = [];
  const sandbox = {
    document: { documentElement: { getAttribute: (k) => (k === 'lang' ? pageLang : null) } },
    navigator: {
      languages: opts.languages,
      language: opts.language,
      userLanguage: opts.userLanguage,
      userAgent: opts.userAgent,
      webdriver: opts.webdriver
    },
    location: { replace: (u) => calls.push(String(u)) },
    localStorage: {
      getItem: (k) => (k in store ? store[k] : null),
      setItem: () => {}
    }
  };
  let threw = false;
  try {
    vm.runInNewContext(script, sandbox, { filename: 'resume-lang-bootstrap.js' });
  } catch (e) {
    threw = true;
  }
  return { calls, threw };
}

function langCheck(name, script, pageLang, opts, expected) {
  const r = runLang(script, pageLang, opts);
  const pass = !r.threw && JSON.stringify(r.calls) === JSON.stringify(expected);
  return { name, pass, expected, calls: r.calls, threw: r.threw };
}

const langCases = [
  langCheck('EN resume, saved=ru -> ru/resume/', enScript, 'en', { saved: 'ru', language: 'en' }, ['ru/resume/']),
  langCheck('EN resume, ru-preferred browser -> ru/resume/', enScript, 'en', { language: 'ru-RU' }, ['ru/resume/']),
  langCheck('EN resume, en-preferred browser -> stay', enScript, 'en', { language: 'en-US' }, []),
  langCheck('EN resume, saved=en, ru-preferred browser -> stay', enScript, 'en', { saved: 'en', language: 'ru' }, []),
  langCheck('EN resume, googlebot, ru-preferred -> stay', enScript, 'en', {
    userAgent: 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)', language: 'ru-RU'
  }, []),
  langCheck('RU resume, saved=en -> ../resume/', ruScript, 'ru', { saved: 'en', language: 'ru' }, ['../resume/']),
  langCheck('RU resume, en-preferred browser -> ../resume/', ruScript, 'ru', { language: 'en-US' }, ['../resume/']),
  langCheck('RU resume, ru-preferred browser -> stay', ruScript, 'ru', { language: 'ru-RU' }, []),
  langCheck('RU resume, saved=ru, en-preferred browser -> stay', ruScript, 'ru', { saved: 'ru', language: 'en' }, []),
  langCheck('RU resume, bingbot, en-preferred -> stay', ruScript, 'ru', {
    userAgent: 'Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)', language: 'en-US'
  }, [])
];

const report = { en, ru, langBootstrap: langCases };
console.log(JSON.stringify(report, null, 2));

let pass = true;
['en', 'ru'].forEach((lang) => {
  Object.entries(report[lang]).forEach(([k, v]) => {
    if (k === 'relativeRefs') return;
    if (v === false || (Array.isArray(v) && v.length)) {
      pass = false;
      console.error('FAIL [' + lang + ']:', k, v);
    }
  });
});
langCases.forEach((c) => {
  if (!c.pass) { pass = false; console.error('FAIL [lang]:', c.name, c); }
});

if (!pass) process.exit(1);
console.log('\n✓ ALL RESUME PRERENDER + LANGUAGE CHECKS PASSED (EN + RU)');
