/* Headless smoke test for the pre-rendered static site.

   The site is generated at build time by scripts/generate-site.js from
   data/content.js. This test reads the generated HTML files directly —
   no browser, no JavaScript execution — and verifies that all core
   content is present in raw HTML. That is the no-JS acceptance
   criterion: with JavaScript disabled, every section, project, link,
   team member, social and footer entry must still be visible.
*/
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');

/* Extract the inner HTML of <tag id="..."> ... </tag> (tag-depth aware). */
function innerOf(html, id) {
  const re = new RegExp('<([a-zA-Z][a-zA-Z0-9]*)\\b[^>]*\\bid="' + id + '"[^>]*>');
  const m = re.exec(html);
  if (!m) return null;
  const tag = m[1];
  const openEnd = m.index + m[0].length;
  const openRe = new RegExp('<' + tag + '\\b', 'g');
  const closeRe = new RegExp('</' + tag + '>', 'g');
  let depth = 1;
  let i = openEnd;
  openRe.lastIndex = i;
  closeRe.lastIndex = i;
  for (;;) {
    const o = openRe.exec(html);
    const c = closeRe.exec(html);
    if (!c) return null;
    if (o && o.index < c.index) { depth += 1; i = o.index + 1; }
    else { depth -= 1; if (depth === 0) return html.slice(openEnd, c.index); i = c.index + 1; }
    openRe.lastIndex = i;
    closeRe.lastIndex = i;
  }
}

function runChecks(html, lang) {
  const r = {};
  const add = (name, ok) => { r[name] = !!ok; };
  const isRu = lang === 'ru';

  /* --- Build marker + architecture --- */
  add('generated-banner', html.includes('Generated by scripts/generate-site.js'));
  add('no-content-script', !/<script[^>]*src="[^"]*data\/content\.js"/.test(html));

  /* --- Metadata / SEO present in raw HTML --- */
  add('html-lang', html.includes('<html lang="' + lang + '"'));
  add('title', /<title>[^<]+<\/title>/.test(html));
  add('description', /name="description" content="[^"]+"/.test(html));
  add('canonical', html.includes('rel="canonical"') &&
    html.includes(isRu ? 'https://eryyynit.github.io/ru/">' : 'https://eryyynit.github.io/">'));
  add('hreflang', html.includes('hreflang="en"') && html.includes('hreflang="ru"') && html.includes('hreflang="x-default"'));
  add('og', html.includes('property="og:title"') && html.includes('property="og:image"'));
  add('twitter', html.includes('name="twitter:card"') && html.includes('name="twitter:image"'));

  /* --- Navigation / anchors / accessibility --- */
  ['home', 'projects', 'paths', 'game', 'about', 'work', 'build', 'findme', 'support'].forEach((id) => {
    add('anchor-' + id, html.includes('id="' + id + '"'));
  });
  // Game-specific content moved off the home page.
  add('no-team-on-home', !html.includes('id="team"'));
  add('no-game-gallery-on-home', !innerOf(html, 'game-gallery'));
  add('no-game-facts-on-home', !innerOf(html, 'game-facts'));
  add('skip-link', html.includes('class="skip-link"'));
  add('semantic-nav', /<nav\b/.test(html) && /<footer\b/.test(html) && /<main\b/.test(html));

  /* --- Hero / About / Work-with-me (static skeleton) --- */
  add('hero-role', html.includes(isRu ? 'Backend-разработчик' : 'Backend Developer'));
  add('hero-title', html.includes(isRu ? 'вчера не было' : 'weren\'t here yesterday'));
  add('hero-game-cta', html.includes(isRu ? 'href="../game/"' : 'href="game/"') && html.includes('UndeadOverhaul'));
  add('about-heading', html.includes(isRu ? 'Разработчик за этой страницей' : 'The developer behind this page'));
  add('work-cta', html.includes('https://t.me/eprintln'));

  /* --- What I build --- */
  const build = innerOf(html, 'build-grid') || '';
  add('build-cards', (build.match(/<article class="card build-card reveal">/g) || []).length === 3);
  add('build-titles', isRu
    ? build.includes('Backend') && build.includes('Инфраструктура') && build.includes('Эксперименты')
    : build.includes('Backend') && build.includes('Infrastructure') && build.includes('Experiments'));
  add('build-tech', build.includes('Kubernetes') && build.includes('FastAPI'));

  /* --- Two paths (developer / game fork) --- */
  const paths = innerOf(html, 'paths-grid') || '';
  add('paths-cards', (paths.match(/<article class="card path-card reveal">/g) || []).length === 2);
  add('paths-dev', isRu
    ? paths.includes('Разработка') && paths.includes('Резюме') && paths.includes('github.com/EryyynIT')
    : paths.includes('Developer') && paths.includes('Resume') && paths.includes('github.com/EryyynIT'));
  add('paths-game', isRu
    ? paths.includes('Игра') && paths.includes('Открыть UndeadOverhaul') && paths.includes('t.me/undeadoverhaul')
    : paths.includes('Game') && paths.includes('Explore UndeadOverhaul') && paths.includes('t.me/undeadoverhaul'));
  add('paths-dev-resume-link', paths.includes(isRu ? 'href="../resume/"' : 'href="resume/"'));
  add('paths-game-page-link', paths.includes(isRu ? 'href="../game/"' : 'href="game/"'));

  /* --- Projects: selected work + experiments, no flagship on home --- */
  const proj = innerOf(html, 'projects-grid') || '';
  add('projects-featured-group', proj.includes('class="projects-featured"'));
  add('projects-compact-group', proj.includes('class="projects-compact"'));
  add('projects-no-flagship', !proj.includes('project-card--flagship') && !proj.includes('>UndeadOverhaul</h3>'));
  add('projects-all-titles',
    proj.includes('>ADNova</h3>') &&
    proj.includes('>Async Payment Processing Service</h3>') &&
    proj.includes('>queue</h3>') &&
    proj.includes('>MailingTGBot</h3>') &&
    proj.includes('>go-exercises</h3>') &&
    proj.includes('>Tic-Tac-ToeAI</h3>'));
  add('projects-adnova-commercial', proj.includes('status-badge commercial') && proj.includes('commercial-note'));
  add('projects-github-links',
    proj.includes('https://github.com/EryyynIT/async-payment-processing-service') &&
    proj.includes('https://github.com/EryyynIT/queue') &&
    proj.includes('https://github.com/EryyynIT/MailingTGBot') &&
    proj.includes('https://github.com/EryyynIT/go-exercises') &&
    proj.includes('https://github.com/EryyynIT/Tic-Tac-ToeAI'));
  add('projects-group-labels', isRu
    ? proj.includes('Избранные проекты') && proj.includes('Другие эксперименты') && !proj.includes('Selected work')
    : proj.includes('Selected work') && proj.includes('More experiments'));
  add('projects-no-undefined', !/undefined|\[object Object\]/i.test(proj));

  const note = innerOf(html, 'projects-note') || '';
  add('projects-note-link', note.includes('https://github.com/EryyynIT') && note.includes(isRu ? 'на GitHub' : 'on GitHub'));

  /* --- Currently building (terminal) --- */
  const building = innerOf(html, 'building-lines') || '';
  add('building-lines', (building.match(/role="listitem"/g) || []).length === 3);
  add('building-game-link', building.includes('game/') && building.includes('UndeadOverhaul'));

  /* --- UndeadOverhaul teaser (home: 1 asset + status + CTA) --- */
  const teaser = innerOf(html, 'game-teaser') || '';
  add('game-teaser-present', teaser.length > 80);
  add('game-teaser-status', teaser.includes(isRu ? 'В разработке' : 'In development'));
  add('game-teaser-cover', teaser.includes('assets/game/cover.svg') && teaser.includes('game-teaser-media'));
  add('game-teaser-cta', teaser.includes(isRu ? 'Открыть UndeadOverhaul' : 'Explore UndeadOverhaul') &&
    teaser.includes(isRu ? 'href="../game/"' : 'href="game/"'));
  add('game-teaser-devlog', teaser.includes('https://t.me/undeadoverhaul'));

  /* --- Find me (socials, grouped discovery) --- */
  const socials = innerOf(html, 'social-list') || '';
  add('socials-all',
    (socials.match(/class="social-row"/g) || []).length === 6 &&
    socials.includes('https://github.com/EryyynIT') &&
    socials.includes('https://boosty.to/eryyynit') &&
    socials.includes('https://x.com/EryyynIT') &&
    socials.includes('https://www.tiktok.com/@barbaris.yt') &&
    socials.includes('https://t.me/undeadoverhaul') &&
    socials.includes('https://t.me/eprintln'));
  add('social-groups', isRu
    ? socials.includes('Код / Разработка') && socials.includes('Игра') &&
      socials.includes('Личное / Контент') && socials.includes('Поддержка')
    : socials.includes('Build / Code') && socials.includes('Game') &&
      socials.includes('Personal / Content') && socials.includes('Support'));

  /* --- Support --- */
  const support = innerOf(html, 'support-grid') || '';
  add('support-cards', (support.match(/class="card support-card reveal">/g) || []).length === 2);
  add('support-me', support.includes('https://boosty.to/eryyynit') && support.includes('btn-primary'));
  add('support-artist', support.includes('https://boosty.to/manevr'));
  add('support-intro', (innerOf(html, 'support-intro') || '').length > 40);

  /* --- Footer --- */
  const footerLinks = innerOf(html, 'footer-links') || '';
  add('footer-line', (innerOf(html, 'footer-line') || '').includes(isRu ? 'без фреймворков' : 'no frameworks'));
  add('footer-links',
    footerLinks.includes('https://x.com/EryyynIT') &&
    footerLinks.includes('https://github.com/EryyynIT') &&
    footerLinks.includes('https://boosty.to/eryyynit') &&
    // Relative on purpose: `resume/` and `game/` resolve to the language
    // variant of the current page (/ -> /resume/, /ru/ -> /ru/resume/).
    footerLinks.includes('href="resume/"') &&
    footerLinks.includes('href="game/"') &&
    footerLinks.includes('https://boosty.to/manevr') &&
    footerLinks.includes('#support'));

  /* --- No-JS / content hygiene --- */
  add('no-empty-containers',
    innerOf(html, 'build-grid') !== null &&
    innerOf(html, 'projects-grid') !== null &&
    innerOf(html, 'paths-grid') !== null &&
    innerOf(html, 'game-teaser') !== null &&
    innerOf(html, 'social-list') !== null &&
    innerOf(html, 'support-grid') !== null &&
    innerOf(html, 'footer-links') !== null);
  add('no-placeholder-wording', !html.toLowerCase().includes('placeholder'));
  add('no-personal-hub-url', !html.includes('/personal-hub/'));
  add('no-old-comments', !html.includes('rendered from data/content.js'));

  /* --- Article count (semantic cards): 3 build + 2 paths + 6 projects --- */
  add('article-count', (html.match(/<article/g) || []).length === 11);

  /* --- Relative URL integrity: every relative src/href must resolve --- */
  const refs = [...html.matchAll(/(?:href|src)="([^"]+)"/g)].map((m) => m[1]);
  const relative = refs.filter((u) => !u.startsWith('#') && !u.startsWith('http') && !u.startsWith('data:'));
  const missing = relative
    .map((u) => (isRu && u.startsWith('../') ? u.slice(3) : u))
    .filter((u) => !fs.existsSync(path.join(ROOT, u)));
  add('relative-assets-resolve', missing.length === 0);
  r.relativeRefs = relative;
  r.missingFiles = missing;

  return r;
}

const en = runChecks(read('index.html'), 'en');
const ru = runChecks(read('ru/index.html'), 'ru');

const report = { en, ru };
console.log(JSON.stringify(report, null, 2));

let pass = true;
['en', 'ru'].forEach((lang) => {
  Object.entries(report[lang]).forEach(([k, v]) => {
    if (k === 'relativeRefs') return;
    if (v === false || (Array.isArray(v) && v.length)) {
      pass = false;
      console.error('FAIL [' + lang + ']:', k, v);
    }
  });
});

if (!pass) process.exit(1);
console.log('\n✓ ALL PRE-RENDER CHECKS PASSED (EN + RU)');
