#!/usr/bin/env node
/* =====================================================================
   scripts/generate-site.js
   ---------------------------------------------------------------------
   Personal hub build step.

   The browser must receive pre-rendered semantic HTML — not content
   injected at runtime. This script is the bridge:

       data/content.js   (single source of truth, EN + RU)
              │  build time
              ▼
       scripts/generate-site.js
              │
              ├── index.html        (EN home)
              ├── ru/index.html     (RU home)
              ├── resume/index.html (EN professional profile)
              ├── ru/resume/index.html (RU professional profile)
              ├── game/index.html   (EN UndeadOverhaul page)
              └── ru/game/index.html (RU UndeadOverhaul page)

   Usage:  node scripts/generate-site.js   (or: npm run build)

   The page skeleton (head, navigation, hero, about, footer chrome) is
   preserved verbatim; only the data-driven containers are regenerated
   from data/content.js. The script is idempotent — safe to run again.
   ===================================================================== */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.join(__dirname, '..');
const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');
const write = (p, s) => fs.writeFileSync(path.join(ROOT, p), s);

const BANNER =
  '<!-- Generated by scripts/generate-site.js from data/content.js. ' +
  'Edit data/content.js and run `npm run build`. -->';

/* ---------- Load data/content.js (single source of truth) ---------- */
function loadContent() {
  const code = read('data/content.js');
  const sandbox = { window: {}, console };
  vm.createContext(sandbox);
  vm.runInContext(code, sandbox, { filename: 'data/content.js' });
  const site = (sandbox.window && sandbox.window.SITE_CONTENT) || {};
  if (!site.en || !site.ru) {
    throw new Error('data/content.js must expose window.SITE_CONTENT = { en, ru }');
  }
  return site;
}

/* ---------- Shared helpers (mirror the previous runtime renderer) ---------- */
function esc(str) {
  return String(str == null ? '' : str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function isExternal(url) {
  return String(url).indexOf('http') === 0;
}

function chip(t) {
  return '<span class="chip">' + esc(t) + '</span>';
}

/* ---------- Inline SVG icons (identical to the previous runtime set) ---------- */
const ICONS = {
  x: '<svg viewBox="0 0 24 24" width="18" height="18" fill="currentColor" aria-hidden="true"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/></svg>',
  tiktok: '<svg viewBox="0 0 24 24" width="18" height="18" fill="currentColor" aria-hidden="true"><path d="M12.525.02c1.31-.02 2.61-.01 3.91-.02.08 1.53.63 3.09 1.75 4.17 1.12 1.11 2.7 1.62 4.24 1.79v4.03c-1.44-.05-2.89-.35-4.2-.97-.57-.26-1.1-.59-1.62-.93-.01 2.92.01 5.84-.02 8.75-.08 1.4-.54 2.79-1.35 3.94-1.31 1.92-3.58 3.17-5.91 3.21-1.43.08-2.86-.31-4.08-1.03-2.02-1.19-3.44-3.37-3.65-5.71-.02-.5-.03-1-.01-1.49.18-1.9 1.12-3.72 2.58-4.96 1.66-1.44 3.98-2.13 6.15-1.72.02 1.48-.04 2.96-.04 4.44-.99-.32-2.15-.23-3.02.37-.63.41-1.11 1.04-1.36 1.75-.21.51-.15 1.07-.14 1.61.24 1.64 1.82 3.02 3.5 2.87 1.12-.01 2.19-.66 2.77-1.61.19-.33.4-.67.41-1.06.1-1.79.06-3.57.07-5.36.01-4.03-.01-8.05.02-12.07z"/></svg>',
  telegram: '<svg viewBox="0 0 24 24" width="18" height="18" fill="currentColor" aria-hidden="true"><path d="M11.944 0A12 12 0 0 0 0 12a12 12 0 0 0 12 12 12 12 0 0 0 12-12A12 12 0 0 0 12 0a12 12 0 0 0-.056 0zm4.962 7.224c.1-.002.321.023.465.14a.506.506 0 0 1 .171.325c.016.093.036.306.02.472-.18 1.898-.962 6.502-1.36 8.627-.168.9-.499 1.201-.82 1.23-.696.065-1.225-.46-1.9-.902-1.056-.693-1.653-1.124-2.678-1.8-1.185-.78-.417-1.21.258-1.91.177-.184 3.247-2.977 3.307-3.23.007-.032.014-.15-.056-.212s-.174-.041-.249-.024c-.106.024-1.793 1.14-5.061 3.345-.48.33-.913.49-1.302.48-.428-.008-1.252-.241-1.865-.44-.752-.245-1.349-.374-1.297-.789.027-.216.325-.437.893-.663 3.498-1.524 5.83-2.529 6.998-3.014 3.332-1.386 4.025-1.627 4.476-1.635z"/></svg>',
  'telegram-personal': '<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21.5 2.5 11 13"/><path d="M21.5 2.5 15 21.5l-4-8.5-8.5-4 19-6.5z"/></svg>',
  about: '<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="10" r="3.2"/><path d="M5.8 19a7 7 0 0 1 12.4 0"/></svg>',
  github: '<svg viewBox="0 0 24 24" width="18" height="18" fill="currentColor" aria-hidden="true"><path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/></svg>',
  boosty: '<svg viewBox="0 0 24 24" width="18" height="18" fill="currentColor" aria-hidden="true"><path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z"/></svg>',
  external: '<svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/><path d="M15 3h6v6"/><path d="M10 14L21 3"/></svg>',
  download: '<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 3v12"/><path d="M7 10l5 5 5-5"/><path d="M5 21h14"/></svg>',
  mail: '<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="2.5" y="4.5" width="19" height="15" rx="2"/><path d="M3 6.5l9 6 9-6"/></svg>',
  resume: '<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8z"/><path d="M14 3v5h5"/><path d="M9 13h6M9 17h6"/></svg>'
};

function icon(id) {
  return ICONS[id] || ICONS.external;
}

/* =====================================================================
   Section renderers — produce the same semantic markup the old runtime
   renderer produced, now written directly into the static HTML.
   ===================================================================== */

function renderBuildAreas(c, ctx) {
  return (c.buildAreas || []).map(function (a) {
    var tech = (a.tech || []).map(chip).join('');
    return [
      '<article class="card build-card reveal">',
      '  <h3 class="build-title">' + esc(a.title) + '</h3>',
      '  <p class="build-desc">' + esc(a.desc) + '</p>',
      '  <div class="build-tech">' + tech + '</div>',
      '</article>'
    ].join('\n');
  }).join('\n');
}

function renderFeaturedCard(p, ctx) {
  var href = p.url || '#';
  var hasLink = href !== '#';
  var external = isExternal(href);
  var rel = external ? ' target="_blank" rel="noopener noreferrer"' : '';
  var tech = (p.technologies || []).map(chip).join('');
  var arrow = external ? icon('external') : '<span class="arrow" aria-hidden="true">→</span>';
  var cls = 'card project-card reveal';
  if (p.tier === 'flagship') cls += ' project-card--flagship';
  if (p.commercial) cls += ' commercial';

  var media =
    '<' + (hasLink ? 'a' : 'div') + ' class="project-media"' +
    (hasLink ? ' href="' + esc(href) + '"' + rel + ' tabindex="-1" aria-hidden="true"' : '') + '>' +
      '<img src="' + esc(ctx.asset(p.image)) + '" alt="' + esc(p.imageAlt || '') + '" loading="lazy" width="640" height="360">' +
      '<span class="project-type">' + esc(p.type || '') + '</span>' +
    '</' + (hasLink ? 'a' : 'div') + '>';

  var link = '';
  if (hasLink) {
    link = '<a class="project-link" href="' + esc(href) + '"' + rel + '>' +
      esc(p.urlLabel || ctx.labels.viewProject || 'View project') + arrow + '</a>';
  } else if (p.commercial && p.detailsHref) {
    link = '<p class="commercial-note"><a class="commercial-note-link" href="' + esc(p.detailsHref) + '">' +
      esc(p.detailsLabel || ctx.labels.commercialNote || 'Details available in Resume') +
      '<span class="arrow" aria-hidden="true">→</span></a></p>';
  } else if (p.commercial) {
    link = '<p class="commercial-note">' + esc(ctx.labels.commercialNote || 'Commercial project.') + '</p>';
  }

  return [
    '<article class="' + cls + '">',
    '  ' + media,
    '  <div class="project-body">',
    '    <div class="project-title-row">',
    '      <h3 class="project-title">' + esc(p.title) + '</h3>' +
      (p.status ? '<span class="status-badge' + (p.commercial ? ' commercial' : '') + '">' + esc(p.status) + '</span>' : ''),
    '    </div>',
    '    <p class="project-desc">' + esc(p.description) + '</p>',
    p.why ? '    <p class="project-why">' + esc(p.why) + '</p>' : null,
    tech ? '    <div class="project-tech">' + tech + '</div>' : null,
    '    ' + link,
    '  </div>',
    '</article>'
  ].filter(Boolean).join('\n');
}

function renderCompactRow(p, ctx) {
  var href = p.url || '#';
  var hasLink = href !== '#';
  var external = isExternal(href);
  var rel = external ? ' target="_blank" rel="noopener noreferrer"' : '';
  var tech = (p.technologies || []).map(chip).join('');
  var arrow = external ? icon('external') : '<span class="arrow" aria-hidden="true">→</span>';
  var link = hasLink
    ? '<a class="compact-link" href="' + esc(href) + '"' + rel + '>' +
      esc(p.urlLabel || ctx.labels.viewProject || 'View project') + arrow + '</a>'
    : '';

  return [
    '<article class="compact-row reveal">',
    '  <div class="compact-main">',
    '    <div class="compact-title-row">',
    '      <h3 class="compact-title">' + esc(p.title) + '</h3>' +
      (p.status ? '<span class="status-badge">' + esc(p.status) + '</span>' : ''),
    '    </div>',
    '    <p class="compact-desc">' + esc(p.description) + '</p>',
    tech ? '    <div class="compact-meta">' + tech + '</div>' : null,
    '  </div>',
    link ? '  ' + link : null,
    '</article>'
  ].filter(Boolean).join('\n');
}

function renderProjects(c, ctx) {
  var list = c.projects || [];
  if (!list.length) return '';
  var flagship = list.filter(function (p) { return p.tier === 'flagship'; });
  var featured = list.filter(function (p) { return p.tier === 'featured'; });
  var compact = list.filter(function (p) { return p.tier !== 'flagship' && p.tier !== 'featured'; });
  var featuredCards = flagship.concat(featured);

  var parts = [];
  if (featuredCards.length) {
    parts.push('<h3 class="group-title">' + esc(ctx.labels.projectsFeatured || 'Selected work') + '</h3>');
    parts.push('<div class="projects-featured">');
    parts.push(featuredCards.map(function (p) { return renderFeaturedCard(p, ctx); }).join('\n'));
    parts.push('</div>');
  }
  if (compact.length) {
    parts.push('<h3 class="group-title">' + esc(ctx.labels.projectsMore || 'More experiments') + '</h3>');
    parts.push('<div class="projects-compact">');
    parts.push(compact.map(function (p) { return renderCompactRow(p, ctx); }).join('\n'));
    parts.push('</div>');
  }
  return parts.join('\n');
}

function renderProjectsNote(c, ctx) {
  var gh = c.github;
  if (!gh) return '';
  return esc(ctx.labels.projectsNote || 'More projects are in progress') + ' ' +
    '<a href="' + esc(gh) + '" target="_blank" rel="noopener noreferrer">' +
    esc(ctx.labels.projectsOnGithub || 'on GitHub') + '</a>.';
}

function renderBuilding(c, ctx) {
  var data = c.building || {};
  return (data.lines || []).map(function (l) {
    var link = l.url
      ? '<a class="term-link" href="' + esc(ctx.link(l.url)) + '"' +
        (isExternal(l.url) ? ' target="_blank" rel="noopener noreferrer"' : '') + '>' +
        esc(l.label || ctx.labels.moreLink || 'more') + '</a>'
      : '';
    return '<p class="term-line" role="listitem">' +
      '<span class="term-bullet" aria-hidden="true">▸</span>' +
      '<span class="term-text">' + esc(l.text) + '</span>' +
      link +
      '</p>';
  }).join('\n');
}

function renderGameFacts(c, ctx) {
  var info = c.game || {};
  var rows = [
    { k: ctx.labels.factStatus || 'Status', v: info.status },
    { k: ctx.labels.factTeam || 'Team', v: ctx.labels.teamSize || '2 people' },
    { k: ctx.labels.factRelease || 'Release', v: info.release },
    { k: ctx.labels.factPlatforms || 'Platforms', v: info.platforms && info.platforms.length ? info.platforms.join(' / ') : null }
  ].filter(function (r) { return r.v; });
  return rows.map(function (r) {
    return '<li><span class="fact-label">' + esc(r.k) + '</span><span>' + esc(r.v) + '</span></li>';
  }).join('\n');
}

function renderGameGallery(c, ctx) {
  var items = (c.game && c.game.gallery) || [];
  return items.map(function (g, i) {
    var num = i + 1;
    num = num < 10 ? '0' + num : String(num);
    return [
      '<figure class="game-shot">',
      '  <img src="' + esc(ctx.asset(g.src)) + '" alt="' + esc(g.alt) + '" loading="lazy" width="640" height="360">',
      '  <figcaption>' + esc(g.label) + ' — ' + num + '</figcaption>',
      '</figure>'
    ].join('\n');
  }).join('\n');
}

function renderTeam(c, ctx) {
  return (c.team || []).map(function (m) {
    var links = (m.links || []).map(function (l) {
      return '<a class="btn btn-ghost btn-sm team-link" href="' + esc(l.url) + '" target="_blank" rel="noopener noreferrer">' +
        '<span class="team-link-icon">' + icon(l.id) + '</span>' +
        '<span>' + esc(l.label) + '</span>' +
        '<span class="team-link-ext">' + icon('external') + '</span>' +
        '</a>';
    }).join('');

    return [
      '<article class="card team-card reveal">',
      '  <div class="team-top">',
      '    <span class="team-avatar" aria-hidden="true">' + esc(m.avatarText || '?') + '</span>',
      '    <div>',
      '      <h3 class="team-name">' + esc(m.name) + '</h3>',
      '      <p class="team-role">' + esc(m.role) + '</p>',
      '    </div>',
      '  </div>',
      '  <p class="team-about">' + esc(m.about) + '</p>',
      m.note ? '  <p class="team-note">' + esc(m.note) + '</p>' : null,
      '  <div class="team-links">' + links + '</div>',
      '</article>'
    ].filter(Boolean).join('\n');
  }).join('\n');
}

/* ---------- Two paths (home fork: developer / game) ---------- */
function renderPathCard(p, ctx) {
  var links = (p.links || []).map(function (l) {
    var external = isExternal(l.url);
    var rel = external ? ' target="_blank" rel="noopener noreferrer"' : '';
    var arrow = external ? icon('external') : '<span class="arrow" aria-hidden="true">→</span>';
    return '<li><a class="path-link" href="' + esc(ctx.link(l.url)) + '"' + rel + '>' +
      '<span>' + esc(l.label) + '</span>' + arrow + '</a></li>';
  }).join('\n');
  return [
    '<article class="card path-card reveal">',
    '  <div class="path-head">',
    '    <span class="path-tag" aria-hidden="true">' + esc(p.tag || '') + '</span>',
    '    <div>',
    '      <h3 class="path-title">' + esc(p.title || '') + '</h3>',
    '      <p class="path-message">' + esc(p.message || '') + '</p>',
    '    </div>',
    '  </div>',
    '  <ul class="path-links">' + links + '</ul>',
    '</article>'
  ].join('\n');
}

function renderPaths(c, ctx) {
  var p = c.paths || {};
  var dev = p.developer || {};
  var game = p.game || {};
  return renderPathCard(dev, ctx) + '\n' + renderPathCard(game, ctx);
}

/* ---------- UndeadOverhaul teaser (home: 1 asset + one CTA) ----------
   Home only tells visitors the project exists. The full game context —
   team, media, devlog, support — lives on /game/, so the teaser must
   stay shallow: title (in the section header), short description, one
   visual asset and exactly one primary CTA. No devlog / Telegram links,
   no team listing, no support links here. */
function renderGameTeaser(c, ctx) {
  var g = c.game || {};
  var url = ctx.link('game/');
  return [
    '<div class="game-teaser-layout">',
    '  <a class="game-teaser-media" href="' + esc(url) + '" tabindex="-1" aria-hidden="true">',
    '    <img src="' + esc(ctx.asset(g.cover || 'assets/game/cover.svg')) + '" alt="' + esc((g.title || '') + ' — cover art') + '" width="800" height="450">',
    '  </a>',
    '  <div class="game-teaser-info">',
    '    <p class="game-status"><span class="status-dot" aria-hidden="true"></span><span>' + esc(g.status || '') + '</span></p>',
    '    <p class="game-desc">' + esc(g.teaser || g.description || '') + '</p>',
    '    <div class="game-cta">',
    '      <a class="btn btn-primary" href="' + esc(url) + '">' + esc(ctx.labels.exploreGame || 'Explore UndeadOverhaul') + '<span class="arrow" aria-hidden="true">→</span></a>',
    '    </div>',
    '  </div>',
    '</div>'
  ].join('\n');
}

/* ---------- UndeadOverhaul page (dedicated route /game/) ---------- */
function renderGameCover(g, ctx) {
  return '<img class="game-hero-cover" src="' + esc(ctx.asset(g.cover || 'assets/game/cover.svg')) +
    '" alt="' + esc((g.title || '') + ' — cover art') + '" width="800" height="450">';
}

function renderGameLinks(c, ctx) {
  var g = c.game || {};
  var rows = [];
  if (g.devlog && g.devlog.url) {
    rows.push({
      id: 'telegram',
      label: g.devlog.label || ctx.labels.devlogOnTelegram || 'Devlog on Telegram',
      handle: g.devlog.handle || '',
      note: g.devlog.note || '',
      url: g.devlog.url
    });
  }
  var dev = (c.team || [])[0] || {};
  (dev.links || []).forEach(function (l) {
    rows.push({ id: l.id, label: l.label, handle: '', note: dev.name || '', url: l.url });
  });
  var artist = (c.team || [])[1] || {};
  (artist.links || []).forEach(function (l) {
    rows.push({ id: l.id, label: l.label, handle: '', note: (l.id === 'boosty' ? artist.note : artist.name) || '', url: l.url });
  });
  return renderSocialRows(rows, ctx);
}

function renderSocialRows(rows, ctx) {
  return rows.map(function (s) {
    return [
      '<li>',
      '  <a class="social-row" href="' + esc(s.url) + '" target="_blank" rel="noopener noreferrer">',
      '    <span class="social-icon">' + icon(s.id) + '</span>',
      '    <span class="social-text">',
      '      <span class="social-label">' + esc(s.label) + '</span>',
      '      <span class="social-handle">' + esc(s.handle || '') + '</span>',
      '      <span class="social-note">' + esc(s.note || '') + '</span>',
      '    </span>',
      '    <span class="social-arrow" aria-hidden="true">' + icon('external') + '</span>',
      '  </a>',
      '</li>'
    ].join('\n');
  }).join('\n');
}

/* Find me — one compact discovery area grouped by intent
   (Build / Code, Game, Personal / Content, Support). */
function renderSocials(c, ctx) {
  var socials = c.socials || [];
  var order = [];
  var byGroup = {};
  socials.forEach(function (s) {
    var g = s.group || '';
    if (byGroup[g]) byGroup[g].push(s);
    else { byGroup[g] = [s]; order.push(g); }
  });
  return order.map(function (g) {
    var head = g
      ? '<li class="social-group-head" aria-hidden="true">' + esc(g) + '</li>'
      : '';
    return head + renderSocialRows(byGroup[g], ctx);
  }).join('\n');
}

function renderSupport(c, ctx) {
  var sp = c.support || {};
  var meUrl = c.boosty;
  var meBtn = meUrl
    ? '<a class="btn btn-primary btn-block" href="' + esc(meUrl) + '" target="_blank" rel="noopener noreferrer">' + icon('boosty') + '<span>' + esc(ctx.labels.supportOnBoosty || 'Support on Boosty') + '</span>' + icon('external') + '</a>'
    : '<button class="btn btn-primary btn-block" type="button" disabled title="' + esc(ctx.labels.supportBtnTitle || '') + '">' + icon('boosty') + '<span>' + esc(ctx.labels.supportComingSoon || 'Support on Boosty — coming soon') + '</span></button>';

  var artistUrl = sp.artist && sp.artist.url;
  var artistBtn = artistUrl
    ? '<a class="btn btn-ghost btn-block" href="' + esc(artistUrl) + '" target="_blank" rel="noopener noreferrer">' + icon('boosty') + '<span>' + esc(ctx.labels.supportOnBoosty || 'Support on Boosty') + '</span>' + icon('external') + '</a>'
    : '';

  return [
    '<div class="card support-card reveal">',
    '  <h3 class="support-title">' + esc((sp.me && sp.me.label) || 'Support me') + '</h3>',
    '  <p class="support-desc">' + esc((sp.me && sp.me.description) || '') + '</p>',
    '  ' + meBtn,
    '</div>',
    '<div class="card support-card reveal">',
    '  <h3 class="support-title">' + esc((sp.artist && sp.artist.label) || 'Support the artist') + '</h3>',
    '  <p class="support-desc">' + esc((sp.artist && sp.artist.description) || '') + '</p>',
    artistBtn ? '  ' + artistBtn : null,
    '</div>'
  ].filter(Boolean).join('\n');
}

function renderFooterLinks(c, ctx) {
  var links = (c.footer && c.footer.links) || [];
  return links.map(function (l) {
    var url = l.url;
    if (l.id === 'github' && !url) url = c.github || '';
    if (!url) {
      return '<li><span class="footer-link footer-link-muted" title="GitHub link not set yet — add it in data/content.js (github)">' +
        icon(l.id) + '<span>' + esc(l.label) + '</span></span></li>';
    }
    var external = isExternal(url);
    var rel = external ? ' target="_blank" rel="noopener noreferrer"' : '';
    return '<li><a class="footer-link" href="' + esc(url) + '"' + rel + '>' +
      icon(l.id) + '<span>' + esc(l.label) + '</span></a></li>';
  }).join('\n');
}

/* =====================================================================
   Resume / professional profile renderers (EN + RU)
   ===================================================================== */

function renderResumeMeta(r, ctx) {
  return (r.meta || []).map(function (m) {
    if (m.url) {
      var external = isExternal(m.url);
      return '<li><a href="' + esc(m.url) + '"' +
        (external ? ' target="_blank" rel="noopener noreferrer"' : '') + '>' +
        esc(m.value) + '</a></li>';
    }
    return '<li><span>' + esc(m.value) + '</span></li>';
  }).join('\n');
}

function renderResumePdfCta(r, ctx) {
  var pdf = r.pdf || {};
  if (!pdf.file) return '';
  var href = ctx.asset(pdf.file);
  var name = String(pdf.file).split('/').pop();
  return '<a class="btn btn-primary" href="' + esc(href) + '" download>' +
    icon('download') +
    '<span>' + esc(ctx.labels.resumePdfLabel || 'Download PDF') + '</span>' +
    '</a>' +
    '<p class="resume-pdf-note">PDF · ' + esc(name) + '</p>';
}

function renderResumeEntry(e, ctx) {
  var tech = (e.tech || []).map(chip).join('');
  var head = '<div class="resume-entry-head">' +
    '<div>' +
      '<h4 class="resume-entry-company">' + esc(e.company) + '</h4>' +
      (e.role
        ? '<p class="resume-entry-role">' + esc(e.role) +
          (e.location ? ' · ' + esc(e.location) : '') + '</p>'
        : '') +
    '</div>' +
    (e.period
      ? '<p class="resume-entry-date">' + esc(e.period) +
        (e.duration ? ' · ' + esc(e.duration) : '') + '</p>'
      : '') +
  '</div>';
  var points = (e.points || []).map(function (pt) {
    return '<li>' + esc(pt) + '</li>';
  }).join('\n');
  return [
    '<article class="resume-entry">',
    '  ' + head,
    points ? '  <ul class="resume-entry-points">' + points + '</ul>' : null,
    tech ? '  <div class="resume-entry-tech">' + tech + '</div>' : null,
    e.result
      ? '  <p class="resume-entry-result"><strong>' + esc(ctx.labels.resumeResultLabel || 'Result:') + '</strong> ' +
        esc(e.result) + '</p>'
      : null,
    '</article>'
  ].filter(Boolean).join('\n');
}

function renderResumeExperience(r, ctx) {
  return (r.groups || []).map(function (g) {
    var entries = (g.entries || []).map(function (e) {
      return renderResumeEntry(e, ctx);
    }).join('\n');
    var cls = 'resume-group' + (g.highlight ? ' resume-group--highlight' : '');
    return [
      '<div class="' + cls + '">',
      '  <h3 class="resume-group-title">' + esc(g.label) + '</h3>',
      '  <div class="resume-entries">',
      entries,
      '  </div>',
      '</div>'
    ].join('\n');
  }).join('\n');
}

function renderResumeSkills(r, ctx) {
  return (r.skills || []).map(function (s) {
    var items = (s.items || []).map(chip).join('');
    return [
      '<div class="resume-skill">',
      '  <h4 class="resume-skill-cat">' + esc(s.category) + '</h4>',
      '  <div class="resume-skill-items">' + items + '</div>',
      '</div>'
    ].join('\n');
  }).join('\n');
}

function renderResumeContact(r, ctx) {
  return (r.contactLinks || []).map(function (l) {
    return [
      '<a class="resume-contact-row" href="' + esc(l.url) + '"' +
        (isExternal(l.url) ? ' target="_blank" rel="noopener noreferrer"' : '') + '>',
      '  <span class="resume-contact-icon">' + icon(l.icon) + '</span>',
      '  <span class="resume-contact-text">',
      '    <span class="resume-contact-label">' + esc(l.label) + '</span>',
      '    <span class="resume-contact-value">' + esc(l.value) + '</span>',
      '  </span>',
      '  <span class="social-arrow" aria-hidden="true">' + icon('external') + '</span>',
      '</a>'
    ].join('\n');
  }).join('\n');
}

/* ---------- Resume container map: id -> generated inner HTML ---------- */
function buildResumeSectionMap(content, ctx) {
  var r = content.resume || {};
  return {
    'resume-name': esc(r.name || ''),
    'resume-role': esc(r.role || ''),
    'resume-meta': renderResumeMeta(r, ctx),
    'resume-pdf-cta': renderResumePdfCta(r, ctx),
    'resume-summary': esc(r.summary || ''),
    'resume-experience': renderResumeExperience(r, ctx),
    'resume-skills': renderResumeSkills(r, ctx),
    'resume-contact-title': esc(r.contactHeading || ''),
    'resume-contact-sub': esc(r.contactSub || ''),
    'resume-contact': renderResumeContact(r, ctx),
    'year': String(new Date().getFullYear())
  };
}

/* ---------- Container map: id -> generated inner HTML (home) ----------
   Home is the directional hub: identity, selected work, the two paths,
   a shallow game teaser, a short about, discovery and support. Build
   areas and the workbench terminal live on the dedicated /about/ page
   (see buildAboutSectionMap below). */
function buildSectionMap(content, ctx) {
  var c = content;
  return {
    'projects-grid': renderProjects(c, ctx),
    'projects-note': renderProjectsNote(c, ctx),
    'paths-grid': renderPaths(c, ctx),
    'game-teaser': renderGameTeaser(c, ctx),
    'social-list': renderSocials(c, ctx),
    'support-grid': renderSupport(c, ctx),
    'support-intro': c.support && c.support.intro ? esc(c.support.intro) : '',
    'footer-line': c.footer && c.footer.line ? esc(c.footer.line) : '',
    'footer-links': renderFooterLinks(c, ctx),
    'year': String(new Date().getFullYear())
  };
}

/* ---------- Container map: id -> generated inner HTML (/about/) ----------
   /about/ is the complete personal context. It receives the full story
   and the "what I build" / "right now" material that used to sit on the
   home page, so nothing is lost — it is simply relocated to the page
   that explains instead of pointing. */
function buildAboutSectionMap(content, ctx) {
  var c = content;
  return {
    'about-name': esc((c.about && c.about.name) || 'EryyynIT'),
    'about-role': esc((c.about && c.about.role) || (c.site && c.site.role) || ''),
    'about-intro': esc((c.about && c.about.intro) || ''),
    'about-story': renderAboutStory(c, ctx),
    'about-build-grid': renderBuildAreas(c, ctx),
    'about-building-lines': renderBuilding(c, ctx),
    'year': String(new Date().getFullYear())
  };
}

function renderAboutStory(c, ctx) {
  var story = (c.about && c.about.story) || [];
  return story.map(function (p) {
    return '<p>' + esc(p) + '</p>';
  }).join('\n');
}

/* ---------- Container map: id -> generated inner HTML (game page) ---------- */
function buildGameSectionMap(content, ctx) {
  var c = content;
  var g = c.game || {};
  return {
    'game-title': esc(g.title || ''),
    'game-tagline': esc(g.tagline || ''),
    'game-status': g.status ? esc(g.status) : '',
    'game-cover': renderGameCover(g, ctx),
    'game-desc': g.description ? esc(g.description) : '',
    'game-facts': renderGameFacts(c, ctx),
    'game-gallery': renderGameGallery(c, ctx),
    'game-team': renderTeam(c, ctx),
    'game-links': renderGameLinks(c, ctx),
    'game-support-intro': c.support && c.support.intro ? esc(c.support.intro) : '',
    'game-support-grid': renderSupport(c, ctx),
    'year': String(new Date().getFullYear())
  };
}

/* ---------- Replace the inner content of <tag id="..."> ... </tag> ---------- */
function replaceContainer(html, id, inner) {
  var openRe = new RegExp('<([a-zA-Z][a-zA-Z0-9]*)\\b[^>]*\\bid="' + id + '"[^>]*>');
  var m = openRe.exec(html);
  if (!m) throw new Error('Container #' + id + ' not found in HTML');
  var tag = m[1];
  var openEnd = m.index + m[0].length;

  var nextOpen = new RegExp('<' + tag + '\\b', 'g');
  var nextClose = new RegExp('</' + tag + '>', 'g');
  var depth = 1;
  var i = openEnd;
  nextOpen.lastIndex = i;
  nextClose.lastIndex = i;
  var closeEnd = -1;

  for (;;) {
    var o = nextOpen.exec(html);
    var c = nextClose.exec(html);
    if (!c) throw new Error('Unmatched container #' + id);
    if (o && o.index < c.index) {
      depth += 1;
      i = o.index + 1;
    } else {
      depth -= 1;
      if (depth === 0) { closeEnd = c.index; break; }
      i = c.index + 1;
    }
    nextOpen.lastIndex = i;
    nextClose.lastIndex = i;
  }

  // Keep the container's own closing tag: `after` starts at closeEnd.
  var before = html.slice(0, openEnd);
  var after = html.slice(closeEnd);
  return before + '\n' + inner + '\n' + after;
}

/* ---------- Fill one language page ---------- */
function fillPage(html, lang, content) {
  var ctx = {
    labels: content.labels || {},
    asset: function (src) { return lang === 'ru' ? '../' + String(src || '') : String(src || ''); },
    link: function (url) {
      var u = String(url || '');
      if (lang !== 'ru') return u;
      if (u.indexOf('http') === 0 || u.indexOf('#') === 0 || u.indexOf('mailto:') === 0) return u;
      return '../' + u;
    }
  };

  // Build marker (idempotent).
  if (html.indexOf('Generated by scripts/generate-site.js') === -1) {
    html = html.replace('<!DOCTYPE html>', '<!DOCTYPE html>\n' + BANNER);
  }

  // data/content.js is a build-time source only — browsers receive
  // pre-rendered HTML and do not need to download it.
  html = html.replace(/\n[ \t]*<script src="(?:\.\.\/)?data\/content\.js"><\/script>\n/g, '\n');

  var map = buildSectionMap(content, ctx);
  Object.keys(map).forEach(function (id) {
    html = replaceContainer(html, id, map[id]);
  });

  return html;
}

/* ---------- Fill one game page (dedicated UndeadOverhaul route) ---------- */
function fillGamePage(html, lang, content) {
  // /game/ and /ru/game/ are one level deep — assets and internal
  // relative links need one extra "../" compared to the home pages.
  var prefix = lang === 'ru' ? '../../' : '../';
  var ctx = {
    labels: content.labels || {},
    asset: function (src) { return prefix + String(src || ''); },
    link: function (url) {
      var u = String(url || '');
      if (u.indexOf('http') === 0 || u.indexOf('#') === 0 || u.indexOf('mailto:') === 0) return u;
      return prefix + u;
    }
  };

  if (html.indexOf('Generated by scripts/generate-site.js') === -1) {
    html = html.replace('<!DOCTYPE html>', '<!DOCTYPE html>\n' + BANNER);
  }

  var map = buildGameSectionMap(content, ctx);
  Object.keys(map).forEach(function (id) {
    html = replaceContainer(html, id, map[id]);
  });

  return html;
}

/* ---------- Fill one resume page (document-like, content from data/content.js) ---------- */
function fillResumePage(html, lang, content, assetPrefix) {
  var ctx = {
    labels: content.labels || {},
    asset: function (src) { return assetPrefix + String(src || ''); }
  };

  // Build marker (idempotent).
  if (html.indexOf('Generated by scripts/generate-site.js') === -1) {
    html = html.replace('<!DOCTYPE html>', '<!DOCTYPE html>\n' + BANNER);
  }

  var map = buildResumeSectionMap(content, ctx);
  Object.keys(map).forEach(function (id) {
    html = replaceContainer(html, id, map[id]);
  });

  return html;
}

/* ---------- Fill one about page (personal context, /about/) ---------- */
function fillAboutPage(html, lang, content) {
  // /about/ and /ru/about/ are one level deep, like the resume pages —
  // assets and internal relative links need one extra "../" compared to
  // the home pages.
  var prefix = lang === 'ru' ? '../../' : '../';
  var ctx = {
    labels: content.labels || {},
    asset: function (src) { return prefix + String(src || ''); },
    link: function (url) {
      var u = String(url || '');
      if (u.indexOf('http') === 0 || u.indexOf('#') === 0 || u.indexOf('mailto:') === 0) return u;
      return prefix + u;
    }
  };

  // Build marker (idempotent).
  if (html.indexOf('Generated by scripts/generate-site.js') === -1) {
    html = html.replace('<!DOCTYPE html>', '<!DOCTYPE html>\n' + BANNER);
  }

  var map = buildAboutSectionMap(content, ctx);
  Object.keys(map).forEach(function (id) {
    html = replaceContainer(html, id, map[id]);
  });

  return html;
}

/* ---------- Build ---------- */
function generate() {
  var site = loadContent();
  var enHtml = fillPage(read('index.html'), 'en', site.en);
  var ruHtml = fillPage(read('ru/index.html'), 'ru', site.ru);
  write('index.html', enHtml);
  write('ru/index.html', ruHtml);

  // Resume / professional profile pages (EN + RU).
  var resumeEnHtml = fillResumePage(read('resume/index.html'), 'en', site.en, '../');
  var resumeRuHtml = fillResumePage(read('ru/resume/index.html'), 'ru', site.ru, '../../');
  write('resume/index.html', resumeEnHtml);
  write('ru/resume/index.html', resumeRuHtml);

  // Personal / about pages (EN + RU).
  var aboutEnHtml = fillAboutPage(read('about/index.html'), 'en', site.en);
  var aboutRuHtml = fillAboutPage(read('ru/about/index.html'), 'ru', site.ru);
  write('about/index.html', aboutEnHtml);
  write('ru/about/index.html', aboutRuHtml);

  // UndeadOverhaul dedicated game pages (EN + RU).
  var gameEnHtml = fillGamePage(read('game/index.html'), 'en', site.en);
  var gameRuHtml = fillGamePage(read('ru/game/index.html'), 'ru', site.ru);
  write('game/index.html', gameEnHtml);
  write('ru/game/index.html', gameRuHtml);

  console.log('✓ index.html, ru/index.html, resume/, ru/resume/, about/, ru/about/, game/, ru/game/ regenerated from data/content.js');
}

if (require.main === module) {
  generate();
}

module.exports = { generate };
